.github/workflows/rust.yml
I've chosen not to deny warnings in CI because we currently have warnings.
Once #1 lands, we can enforce cleanliness from warnings
=> Create initial CI

Cargo.lock, Cargo.toml
=> Allow selecting the glazier backend on Linux

Cargo.lock, Cargo.toml, src/app_main.rs, src/test_scenes.rs, src/text.rs, src/widget/core.rs
Updates dependencies so we're on the latest version of vello.
=> Update vello to latest

Cargo.lock
=> fix: Update swash

crates/xilem_html/src/event/mod.rs
I tried to leave this as a review last night but unfortunately [this](https://github.com/orgs/community/discussions/10369) happened.
=> xilem_html: OnEvent: don't handle children's messages

crates/xilem_svg/src/kurbo_shape.rs
=> Fix cargo fmt.

Cargo.lock, crates/xilem_html/src/element/mod.rs, crates/xilem_html/src/view_ext.rs, crates/xilem_html/web_examples/todomvc/Cargo.toml, crates/xilem_html/web_examples/todomvc/src/lib.rs, crates/xilem_html/web_examples/todomvc/src/state.rs
This patch allows all tasks to be toggled complete/incomplete.
There is a bug where when the filter changes, the 'completed' check gets out of sync with its task. I haven't nailed down the exact cause yet.
=> Implement more of the TodoMVC functionality.

README.md
This brings over elements from the Vello `README.md`.
=> README: Add community, license, contribution, badges.

crates/xilem_core/src/view/adapt.rs
I'm not sure I'll actually need this but I think there shouldn't be any serious downsides, either way.
=> Add a default for generic parameter F of Adapt

crates/xilem_html/src/view_ext.rs
More convenient than `{Adapt, AdaptState}::new`.
=> xilem_html: Add ViewExt::{adapt, adapt_state}

crates/xilem_html/src/lib.rs
No point in having it if it's not nameable ^^
=> xilem_html: Re-export Memoize from crate root

Cargo.toml, crates/xilem_core/Cargo.toml, crates/xilem_html/Cargo.toml, crates/xilem_html/web_examples/counter/Cargo.toml, crates/xilem_html/web_examples/counter_untyped/Cargo.toml, crates/xilem_html/web_examples/todomvc/Cargo.toml, crates/xilem_svg/Cargo.toml
This PR adds a bunch of `Cargo.toml` properties so that they better represent their respective packages. I also utilized the workspace variables for commonly reusable properties.
=> Fill out and clean up all the `Cargo.toml` files.

README.md
This is the companion PR to [glazier#134](https://github.com/linebender/glazier/pull/134) to keep the dependency info in sync.
=> Add Wayland dev package dependency info to `README.md`.

crates/xilem_web/src/app.rs, crates/xilem_web/src/context.rs, crates/xilem_web/src/vecmap.rs, crates/xilem_web/web_examples/todomvc/src/state.rs, examples/hello.rs, examples/taffy.rs, src/geometry.rs, src/view/taffy_layout.rs, src/widget/button.rs, src/widget/core.rs, src/widget/piet_scene_helpers.rs, src/widget/switch.rs
This doesn't enable the lint as I have a subsequent follow-up PR coming for that.
=> clippy: Fix semicolon_if_nothing_returned lints.

src/app_main.rs, src/widget/raw_event.rs, src/widget/scroll_view.rs
Fixes #183
Continues #182
The terminology around this is unclear, but I've tried to add hinting comments as well
=> Uninvert the scroll direction

Cargo.lock, crates/xilem_web/Cargo.toml
Tested some of the examples with `trunk serve` and interacted with them.
=> xilem_web: Update gloo, remove "utils" feature.

Cargo.lock, crates/masonry/Cargo.toml, crates/masonry/examples/calc.rs, crates/masonry/examples/custom_widget.rs, crates/masonry/examples/hello_masonry.rs, crates/masonry/examples/simple_image.rs, crates/masonry/src/event_loop_runner.rs, crates/masonry/src/testing/harness.rs, crates/xilem_masonry/src/lib.rs
This subscriber uses EnvFilter to change its value depending on the RUST_LOG env variable, so log levels can be changed without recompiling the app.
=> Add default subscriber to Masonry

crates/masonry/src/text2/edit.rs, crates/masonry/src/text2/selection.rs
=> Implement underlining for IME areas

README.md
Congrats everyone on v0.1!
Not sure if this is the best styling to go for, but I think it'd be great to link to the new releases
=> Add crates.io and docs.rs links to README.md

masonry/src/text2/backspace.rs, masonry/src/text2/edit.rs, masonry/src/text2/mod.rs
This is followup to #273.
This code originally came from https://github.com/xi-editor/xi-editor/pull/837
I've also brought the tests back
=> Actually use the druid backspace logic

masonry/examples/calc.rs, masonry/examples/custom_widget.rs, masonry/examples/hello_masonry.rs, masonry/examples/simple_image.rs, masonry/src/event_loop_runner.rs, masonry/src/text2/selection.rs, xilem/Cargo.toml, xilem/examples/flex.rs, xilem/examples/mason.rs, xilem/examples/memoization.rs, xilem/examples/to_do_mvc.rs, xilem/src/lib.rs
```
cargo apk run --example mason_android -p xilem
```
There will some followup needed here, of course. But some of that will want to come after xilem#235, when the way to do multiple windows has become clearer
=> Make execution on Android work properly

masonry/src/event_loop_runner.rs
https://github.com/linebender/xilem/assets/1272018/6e9aeefb-f324-4738-9aa2-f54d643631e2
=> Add basic translation of Touch to PointerEvent.

masonry/src/widget/textbox.rs, xilem/examples/mason.rs
Also fix clipping behaviour - previously the textbox outline would be clipped.
=> Fix textboxes with an infinite available width

masonry/src/render_root.rs
Inline `wants_animation_frame`.
Request new frame for both visual and accessibility updates.
=> Tweak code in post_event_processing

masonry/src/tracing_backend.rs
Previously, this had the potential to be quite confusing.
=> Don't create a log file and print its name unless it will be used

xilem_web/web_examples/counter/index.html, xilem_web/web_examples/counter_custom_element/index.html, xilem_web/web_examples/mathml_svg/index.html, xilem_web/web_examples/svgtoy/index.html
These got mixed up in https://github.com/linebender/xilem/pull/142
=> Fix the `head` elements of Xilem Web

Cargo.lock, Cargo.toml
Mostly to double check that the new release is suitable, but formalising the update can't hurt
=> Update to Vello 0.2.1 and wgpu 0.20.1

.github/workflows/ci.yml, masonry/src/widget/widget_pod.rs
Cc @xStrom for the CI change
Cc @PoignardAzur for the Masonry changes
=> Allow Masonry to compile in release mode

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, masonry/README.md, masonry/examples/calc.rs, masonry/src/action.rs, masonry/src/event_loop_runner.rs, masonry/src/widget/label.rs, xilem/Cargo.toml, xilem/README.md, xilem/examples/external_event_loop.rs, xilem/examples/mason.rs, xilem/src/any_view.rs, xilem/src/driver.rs, xilem/src/lib.rs, xilem/src/view/async_repeat.rs, xilem/src/view/mod.rs, xilem_core/Cargo.toml, xilem_core/README.md, xilem_core/src/deferred.rs, xilem_core/src/docs.rs, xilem_core/src/element.rs, xilem_core/src/lib.rs, xilem_core/src/sequence.rs, xilem_core/src/views/fork.rs, xilem_core/src/views/mod.rs, xilem_core/src/views/run_once.rs
Supercedes https://github.com/linebender/xilem/pull/411
This is designed with #417 in mind, to not lock-in to our event loop.
=> Integrate `tokio` for async communication with Xilem

xilem/src/lib.rs
I failed to commit this before merging #423
=> Fix docs on the re-export

xilem/src/view/async_repeat.rs, xilem/src/view/mod.rs
Addresses post-merge review comments in #423.
Also added some stub-like docs.
=> Tweak `async_repeat` and add some docs

xilem/examples/mason.rs, xilem/src/view/flex.rs
This removes the need to force type inference.
=> Use the `boxed` combinator

masonry/src/event.rs, masonry/src/event_loop_runner.rs
device test
* huion kamvas 13 tablet windows 10 platform
=> masonry: add pressure sensitivity to the pen's touch on the screen

xilem_web/src/interfaces.rs
Apropos of #462. Let me know if this should have a test or an example!
=> xilem_web: Add function to set HtmlIFrameElement src attribute

.github/workflows/ci.yml, xilem/Cargo.toml, xilem/examples/calc.rs
This works without any other code modifications.
=> Support running `calc` on Android

masonry/src/tree_arena.rs
@PoignardAzur this is what I meant with the redundancy.
=> masonry: reuse redundant `ArenaRef/Mut` creation code

xilem_web/src/lib.rs
=> xilem_web: Apply props when the element type changes in `replace_inner`

masonry/src/widget/flex.rs
This fixes a regression in the Mason example.
=> Fix Flex widget

.github/workflows/ci.yml
=> Run doctests in ci

masonry/src/widget/portal.rs, xilem/examples/mason.rs, xilem/examples/variable_clock.rs, xilem/src/view/mod.rs, xilem/src/view/portal.rs
This is also added to `variable_clocks` as needed.
This could also be added to `mason`, but I see a worrying amount of lag if I do...
I could do with some help tracking this down.
=> Add the `Portal` view to Xilem

.github/workflows/ci.yml, xilem/Cargo.toml, xilem/examples/to_do_mvc.rs
I'm finding these cargo warnings exceptionally annoying...
=> Setup `to_do_mvc` for Android

masonry/src/tree_arena.rs
Rewrite doc comments
Move find methods to ArenaRef/MutChildren
Create ArenaMapref/Mut in anticipation of future work.
=> Refactor arena code

masonry/src/contexts.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs, masonry/src/widget/widget_ref.rs, masonry/src/widget/widget_state.rs
Add update_stashed pass
Add is_still_interactive method
=> Implement stashed state

masonry/src/widget/flex.rs, masonry/src/widget/grid.rs
(The function is already called in the pass.)
=> Remove superfluous calls to BoxConstraint::debug_check

masonry/src/text/mod.rs
=> masonry: Remove extraneous comment

masonry/src/passes/event.rs
Match how tab focus works in on_text_event pass.
=> Refactor Blur case of on_access_event pass

masonry/examples/calc_masonry.rs, masonry/src/contexts.rs, masonry/src/event.rs, masonry/src/passes/event.rs, masonry/src/render_root.rs, masonry/src/widget/button.rs, masonry/src/widget/checkbox.rs
Remove target field from AccessEvent
=> Add target field to EventCtx

Cargo.lock, Cargo.toml, masonry/src/passes/layout.rs, masonry/src/widget/image.rs
This allows to remove a TODO comment.
=> Update to Kurbo 0.11.1

masonry/examples/calc_masonry.rs, masonry/src/contexts.rs, masonry/src/widget/button.rs, masonry/src/widget/checkbox.rs, masonry/src/widget/image.rs, masonry/src/widget/label.rs, masonry/src/widget/portal.rs, masonry/src/widget/progress_bar.rs, masonry/src/widget/prose.rs, masonry/src/widget/scroll_bar.rs, masonry/src/widget/sized_box.rs, masonry/src/widget/spinner.rs, masonry/src/widget/split.rs, masonry/src/widget/textbox.rs
Remove some redundant request_paint calls
Fixes #585.
=> Add request_render context method

masonry/src/text/text_layout.rs
=> Remove bitrotted comment

masonry/src/app_driver.rs, masonry/src/event_loop_runner.rs, masonry/src/passes/compose.rs, masonry/src/passes/event.rs, masonry/src/passes/layout.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs, masonry/src/widget/widget_state.rs
This implements the last feature from the Pass Specification RFC :tada:
=> Implement fixpoint loop in run_rewrite_passes

masonry/src/passes/update.rs
=> Handle a non-existent previous widget in focus

.github/workflows/ci.yml, tree_arena/README.md, tree_arena/src/lib.rs
Use `cargo rdme` for crate readme and check in CI as mentioned in https://github.com/linebender/xilem/pull/752#discussion_r1867737085
=> use cargo rdme for tree arena

masonry/src/testing/harness.rs
Add scale_factor parameter.
Add links to doc module.
=> Improve documentation of TestHarness

masonry/src/lib.rs
Similar to https://github.com/linebender/xilem/pull/861 this would help creating custom elements while relying on the already used/tested library utilities
=> masonry: make util pub to allow customizing buttons in an app

masonry/src/app/render_root.rs, masonry/src/core/event.rs, masonry/src/core/widget_state.rs, masonry/src/widgets/checkbox.rs, masonry/src/widgets/label.rs, xilem/examples/memoization.rs, xilem_core/src/views/adapt.rs, xilem_web/src/app.rs, xilem_web/src/context.rs, xilem_web/src/elements.rs, xilem_web/src/pointer.rs, xilem_web/src/svg/common_attrs.rs, xilem_web/web_examples/svgtoy/src/main.rs, xilem_web/web_examples/todomvc/src/state.rs
This is a new addition to the "editor period lints". See #867 for context.
=> Fix `clippy::default_trait_access`

xilem/src/view/image.rs
=> Fixing minor artifact.

xilem/src/view/spinner.rs, xilem/src/view/variable_label.rs
Sorry, I should have done this already in #889.
=> Resolving remaining `Label::message` artifacts.

xilem/src/view/image.rs
See [#linebender > Create a channel for Vello?](https://xi.zulipchat.com/#narrow/channel/419691-linebender/topic/Create.20a.20channel.20for.20Vello.3F)
=> Handle renaming of `#gpu` to `#vello`

masonry/src/app/event_loop_runner.rs, masonry/src/core/mod.rs, masonry/src/core/widget.rs, masonry/src/core/widget_mut.rs, masonry/src/core/widget_pod.rs, masonry/src/theme.rs, masonry/src/util.rs, masonry/src/widgets/button.rs, masonry/src/widgets/checkbox.rs, masonry/src/widgets/flex.rs, masonry/src/widgets/grid.rs, masonry/src/widgets/progress_bar.rs, masonry/src/widgets/root_widget.rs, masonry/src/widgets/sized_box.rs, masonry/src/widgets/split.rs, masonry/src/widgets/variable_label.rs, xilem/src/driver.rs, xilem/src/lib.rs, xilem/src/view/flex.rs, xilem/src/view/grid.rs, xilem/src/view/portal.rs, xilem/src/view/progress_bar.rs, xilem/src/view/prose.rs, xilem/src/view/task.rs, xilem/src/view/textbox.rs, xilem/src/view/variable_label.rs, xilem/src/view/worker.rs, xilem/src/view/zstack.rs, xilem_core/src/views/one_of.rs, xilem_web/src/lib.rs
Make missing_docs annotations more granular.
=> Document more items

masonry_core/src/widgets/virtual_scroll.rs, xilem/examples/mason.rs, xilem/examples/virtual_cats.rs, xilem/resources/data/http_cats_status/status.csv, xilem/src/driver.rs, xilem/src/lib.rs, xilem/src/view/image.rs, xilem/src/view/mod.rs, xilem/src/view/virtual_scroll.rs, xilem/src/view/worker.rs, xilem/src/view/zstack.rs, xilem_core/src/message.rs
The semantics of how this integration works are really ugly - it really feels like there's a better model hiding in here somewhere, but that's somewhat by-the-by.
However, it does work.
=> Virtual Scrolling for Xilem

.github/workflows/ci.yml, Cargo.toml, README.md, masonry/README.md, masonry_core/src/core/contexts.rs, masonry_core/src/core/widget.rs, masonry_core/src/core/widget_ref.rs, masonry_core/src/lib.rs, masonry_core/src/testing/helper_widgets.rs, masonry_core/src/util.rs, xilem/README.md, xilem_core/README.md, xilem_web/README.md
=> Streamline Widget trait using trait upcasting

masonry_core/src/widgets/label.rs
While investigating stacking alignment offsets as reported in #933 I noticed that the alignment invalidation logic in `Label::layout` is missing some key parts. This PR addresses that.
* Rename `alignment_changed` to `needs_alignment` to more accurately represent what is being tracked.
* Reset `needs_alignment` back to `false` after aligning.
* Check whether `available_width` has changed since last `layout`, as that requires new alignment.
* Clamp `available_width` to zero as negative values don't make sense but always happen due to the padding subtraction.
=> Fix alignment invalidation in `Label::layout`.

Cargo.lock, Cargo.toml
This includes https://github.com/AccessKit/accesskit/pull/524
=> Update AccessKit Winit to version 25

Cargo.lock, Cargo.toml
Parley is out so we can stop depending on git.
=> Depend on published Parley 0.4.0.

xilem/src/view/prose.rs
This is a small PR that adds font weight to prose. There are other properties, but this is the only one I needed now :)
=> support font weight option on prose (like label)

masonry_core/src/app/render_root.rs, masonry_core/src/core/contexts.rs, masonry_core/src/core/properties.rs, masonry_core/src/core/widget_arena.rs, masonry_core/src/core/widget_mut.rs, masonry_core/src/passes/accessibility.rs, masonry_core/src/passes/anim.rs, masonry_core/src/passes/compose.rs, masonry_core/src/passes/mod.rs, masonry_core/src/passes/paint.rs, masonry_core/src/passes/update.rs, masonry_core/src/properties/background.rs, masonry_core/src/properties/border_color.rs, masonry_core/src/properties/border_width.rs, masonry_core/src/properties/box_shadow.rs, masonry_core/src/properties/corner_radius.rs, masonry_core/src/properties/types/gradient.rs, masonry_core/src/util.rs, masonry_core/src/widgets/sized_box.rs
Create alias for `anymap3::Map<dyn Any + Send + Sync>`.
=> Implement PartialEq, Send and Sync for all Properties

xilem_web/Cargo.toml
[Philipp signaled](https://xi.zulipchat.com/#narrow/channel/419691-linebender/topic/RustWeek.20release.20bonanza/near/517308799) that Xilem Web is ready enough to release too, so let's do it!
=> Prepare to release `xilem_web`.

Cargo.toml, masonry/src/lib.rs, masonry_winit/examples/custom_widget.rs, masonry_winit/src/lib.rs, xilem/examples/components.rs, xilem/examples/elm.rs, xilem/examples/emoji_picker.rs, xilem/examples/external_event_loop.rs, xilem/examples/flex.rs, xilem/examples/mason.rs, xilem/examples/state_machine.rs, xilem/examples/stopwatch.rs, xilem/examples/to_do_mvc.rs, xilem/examples/variable_clock.rs, xilem_core/tests/array_sequence.rs, xilem_core/tests/base_sequence.rs, xilem_core/tests/tuple_sequence.rs, xilem_core/tests/vec_sequence.rs, xilem_web/src/lib.rs, xilem_web/web_examples/counter/src/main.rs, xilem_web/web_examples/counter_custom_element/src/main.rs, xilem_web/web_examples/spawn_tasks/src/main.rs, xilem_web/web_examples/todomvc/src/main.rs
See https://github.com/linebender/linebender.github.io/pull/90
=> Update to the Linbender lint set v6

README.md
=> add docs link to readme

masonry/src/testing/screenshots.rs, masonry/src/util.rs
Move screenshot macros to util.
Export debug_panic.
=> Export more macros from util module

xilem/README.md, xilem/examples/calc.rs, xilem/examples/components.rs, xilem/examples/elm.rs, xilem/examples/emoji_picker.rs, xilem/examples/external_event_loop.rs, xilem/examples/flex.rs, xilem/examples/http_cats.rs, xilem/examples/mason.rs, xilem/examples/memoization.rs, xilem/examples/multiple_windows.rs, xilem/examples/state_machine.rs, xilem/examples/stopwatch.rs, xilem/examples/to_do_mvc.rs, xilem/examples/transforms.rs, xilem/examples/variable_clock.rs, xilem/examples/virtual_cats.rs, xilem/examples/widgets.rs, xilem/src/driver.rs, xilem/src/lib.rs, xilem/src/view/flex.rs, xilem/src/window_options.rs, xilem/src/window_view.rs, xilem_core/src/lib.rs
Writing tests for the driver logic will have to wait for winit 0.31 which introduces
traits like `ActiveEventLoop` and `Window` that we need for testing.
=> xilem: support multiple windows

masonry/screenshots/textbox_outline.png, masonry/screenshots/textbox_selection.png, masonry/src/theme.rs, masonry/src/widgets/textbox.rs, masonry_winit/examples/calc_masonry.rs, masonry_winit/examples/custom_widget.rs, masonry_winit/examples/grid_masonry.rs, masonry_winit/examples/to_do_list.rs, masonry_winit/examples/two_textboxes.rs, masonry_winit/screenshots/example_calc_masonry_initial.png, masonry_winit/screenshots/example_to_do_list_initial.png, xilem/src/view/textbox.rs
Remove default padding around textbox.
Add some padding to examples.
=> Add properties to Textbox

xilem/examples/http_cats.rs, xilem/src/view/worker.rs
Before the Worker view was initialized with a value and the value was only sent with the UnboundedSender if a change was detected via its PartialEq impl. This commit changes the API to instead have you store the UnboundedSender in your app state and directly use it, which has several advantages:
* you can send multiple values at once
* you can send the same value multiple times in a row without having to change it
* you can send from other views
* the code is more clear (explicit send calls vs value changes that may send)
=> xilem: Make Worker take a store_sender callback

placehero/src/components.rs, placehero/src/lib.rs
A quick refactor to make future work easier.
=> Placehero: Move components into their own module

masonry_winit/src/event_loop_runner.rs
std::sync::mpsc::Sender::send does not require &mut self and can be cloned.
=> refactor: stop wrapping signal_sender in Arc<Mutex<..>>

masonry/src/widgets/text_area.rs
Now that we're using `ui-events` and the `ui-events-winit` bridge, we can rely on the `count` field on the pointer state in an event to have the click count rather than tracking this here in each text area.
=> `TextArea`: Use pointer event click count

masonry/src/doc/01_creating_app.md
=> Remove mention of `cargo add winit`

xilem/src/property_tuple.rs, xilem/src/view/button.rs, xilem/src/view/checkbox.rs, xilem/src/view/flex.rs, xilem/src/view/grid.rs, xilem/src/view/indexed_stack.rs, xilem/src/view/label.rs, xilem/src/view/sized_box.rs, xilem/src/view/text_input.rs
=> Xilem: Make visibility for properties visible at call site

masonry_core/src/util.rs
=> Add TODO comment to stroke function

masonry/src/widgets/portal.rs, masonry/src/widgets/virtual_scroll.rs, masonry_core/src/passes/event.rs
This implements the right AccessKit role, properties, and actions for `VirtualScroll`.
=> Accessibility for `VirtualScroll`

masonry/screenshots/rect_big_red_rectangle.png, masonry/screenshots/rect_blue_rectangle.png, masonry/screenshots/rect_hovered_rectangle.png, masonry/src/doc/color_rectangle.rs, masonry/src/doc/implementing_widget.md, masonry/src/doc/mod.rs, masonry/src/doc/snapshots/masonry__doc__color_rectangle__tests__simple_rect.snap, masonry/src/doc/testing_widget.md, masonry/src/doc/widget_properties.md
Add color_rectangle mod which mirror the code examples in the tutorial. Fix bitrot in tutorials surfaced by creating color_rectangle. Add snapshot files for new tests in color_rectangle.
=> Add color_rectangle.rs file

masonry_core/src/app/render_root.rs, masonry_core/src/passes/mutate.rs
=> Add explicit panic to `RenderRoot:edit_root_widget`

masonry/src/properties/mod.rs, masonry/src/properties/progress_bar.rs, masonry/src/theme.rs, masonry/src/widgets/progress_bar.rs
Hi :wave:, I'm looking forward for this library, so I decided to start contributing by solving a simple issue.
Closes #1069
=> Use properties in `ProgressBar`

Cargo.lock, Cargo.toml
See https://github.com/linebender/anymore/releases/tag/v1.0.0
=> Update to Anymore v1.0

masonry/src/theme.rs, masonry/src/widgets/label.rs
Move LABEL_X_PADDING to theme module.
=> Add Padding property to Label

masonry/src/tests/event.rs, masonry_testing/src/harness.rs
Add tests for pointer capture.
Add test for focus-anchoring behavior.
=> Add tests for pointer event pass

masonry/src/tests/event.rs, masonry_testing/src/harness.rs
Add `TestHarness::process_access_event()`  method.
=> Add test for access event pass

.clippy.toml, .github/workflows/ci.yml, masonry/src/doc/testing_widget.md, masonry_core/src/core/widget.rs, masonry_core/src/passes/event.rs, masonry_core/src/passes/update.rs, masonry_winit/src/event_loop_runner.rs, xilem/examples/external_event_loop.rs, xilem_web/src/context.rs, xilem_web/src/one_of.rs
https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/
Main difference for us is lints.
=> Update stable Rust to version 1.89, and fix lints

masonry_winit/src/app_driver.rs, masonry_winit/src/event_loop_runner.rs
Resolves #1309 
Resolves #1308
=> Replace `WindowState` with `is_suspended` boolean

masonry/src/properties/mod.rs, masonry/src/properties/placeholder_color.rs, masonry/src/theme.rs, masonry/src/widgets/text_area.rs, masonry/src/widgets/text_input.rs, masonry_winit/examples/to_do_list.rs, masonry_winit/screenshots/example_to_do_list_initial.png, xilem/examples/to_do_mvc.rs, xilem/src/view/text_input.rs
It's still pretty basic (no properties, no way to set the color or the style or the font, etc), but hey, now we have placeholders!
=> Add placeholder option to text input

masonry_winit/README.md, masonry_winit/examples/calc_masonry.rs, masonry_winit/examples/custom_widget.rs, masonry_winit/examples/grid_masonry.rs, masonry_winit/examples/hello_masonry.rs, masonry_winit/examples/simple_image.rs, masonry_winit/examples/to_do_list.rs, masonry_winit/examples/virtual_fizzbuzz.rs, masonry_winit/src/app_driver.rs, masonry_winit/src/event_loop_runner.rs, masonry_winit/src/lib.rs, xilem/src/app.rs, xilem/src/driver.rs
This is a proposal PR to switch over from tuples to a `NewWindow` struct.
This PR is actually quite similar to #1215
=> Add `NewWindow` struct to encapsulate `(id, attrs, root_widget)`

placehero/src/actions.rs, placehero/src/avatars.rs, placehero/src/components.rs, placehero/src/components/thread.rs, placehero/src/components/timeline.rs, placehero/src/lib.rs, xilem_core/src/environment.rs
This is working towards virtual scrolling support; the use of setting the global state here means that it's not possible for these "pages" to use "local" app state (i.e. lensed state).
=> Placehero: Use an Action for navigation

placehero/src/actions.rs, placehero/src/components.rs, placehero/src/components/timeline.rs, placehero/src/lib.rs
I've been slower to get to this than I would have liked, but the actual implementation wasn't especially difficult.
I haven't tested for edge cases, and currently the storage just grows in an unbounded fashion. But it does appear to be working! See the linked statuses from 2023, around the excellent Rustlab trip.
=> Placehero: Use virtual scrolling for timelines

placehero/src/actions.rs, placehero/src/components.rs, placehero/src/components/timeline.rs, placehero/src/lib.rs, xilem_core/src/view.rs
This has run into difficulty with teardown on the timelines. We work around this here, but a more stable solution would be good.
=> Allow loading a given user's statuses

xilem/examples/to_do_mvc.rs
This matches https://todomvc.com/
=> Use Placeholder text from TodoMVC for to_do_mvc example

masonry_winit/src/app_driver.rs, masonry_winit/src/event_loop_runner.rs, masonry_winit/src/lib.rs, xilem/examples/multiple_windows.rs, xilem/src/app.rs, xilem/src/driver.rs, xilem/src/lib.rs, xilem/src/window_view.rs
Also adds window base-color in Xilem.
=> Simplify multi-window code

Cargo.lock, Cargo.toml
=> Port to Vello's 0.6 release
