linebender/xilem

src/app_main.rs
Small patch that applies the current window scale to the fragment when rendering. Makes the button almost visible on high-dpi Windows :) 
Still needs a fix in glazier to support this on macOS.
=> Apply scale in MainState::render()

Cargo.lock, src/app.rs, src/app_main.rs, src/widget.rs, src/widget/align.rs, src/widget/button.rs, src/widget/core.rs, src/widget/text.rs
Instead of the `paint` method returning a `Rendered` which was just a newtype around `SceneFragment`, pass in `&mut SceneBuilder`. Also store a scene fragment in each `Pod`, which is the storage for these builders.
This change has a number of consequences. Less boilerplate in the paint method, and also less allocation, as the storage can get reused. More importantly, though we don't have the logic for this yet, it sets the stage for retaining scene fragments when widgets don't change.
=> Pass mutable scene builder reference to paint

src/app.rs, src/view.rs, src/view/button.rs, src/view/text.rs, src/widget.rs, src/widget/button.rs, src/widget/core.rs, src/widget/text.rs
This approach has a number of advantages.
- It makes it clear that `set_label` and `set_text` do not themselves set the flags and that these functions are the source of these flags.
- The type is marked as `#[must_use]` so flags are not accidentally missed, which I have done previously when writing views.
- It seems to make the `update` phase unnecessary.
`ChangeFlags` or `Changes` could be some alternative names. The current name could easily be confused with the `update` phase.
=> Introduce ChangeFlags and use it instead of bools to track changes in views

src/app_main.rs, src/widget/core.rs, src/widget/raw_event.rs
Fixes #13, but requires that the active glazier backend listens for mouse leave events. Support under x11 is added in linebender/glazier#45, remaining platforms will be added as time allows.
=> Handle MouseLeft event

Cargo.lock, Cargo.toml, src/app.rs, src/app_main.rs, src/lib.rs, src/test_scenes.rs, src/text.rs, src/widget.rs, src/widget/align.rs, src/widget/button.rs, src/widget/core.rs, src/widget/piet_scene_helpers.rs, src/widget/text.rs
Removes the `piet-scene` dependency and changes `piet-wgsl` to `vello`. Updates all imports for the new crate name. This leaves the git reference as linebender/piet-gpu for now. We can change that to vello in this PR (after the repo is renamed) or in a subsequent one.
=> Update for the piet-wgsl -> vello name change

src/main.rs
I think this is of importance, because it highlights the reactive nature of xilem.
=> Make example an iota more expressive

README.md
I vividly remember that these details used to mean game over for me, when trying out new libraries some years ago.
These things are often undocumented, and I think it's worth putting this up front in the README.
If I find the time, I will see that these instructions are complete (I already have some libraries for development installed, might have missed something others have not installed), and also on pair for ubuntu/pop_os etc.
=> Include Information about needed dependency

src/app_main.rs
It looks like `enabled` and `selected` arguments values for [glazier::menu::Menu::add_item](https://github.com/linebender/glazier/blob/bb4bc453a949b74fc4de16ce6be66b901dcf4ab4/src/menu.rs#L69) call should be swapped. The order changed in [this commit](https://github.com/linebender/druid/commit/7c08b326578aa2b25057f5f1af09f9a6b1f51da4#diff-0f63e54d7096d613a02825d47679656d3cd119abea8bc85c59cba648269b6ae0) in druid-shell, but remained unchanged in Xilem. I cannot see the menu either way on Linux, so cannot verify if it works, but I'm relying on the response to [this comment](https://github.com/linebender/druid/pull/2357#discussion_r1103622282).
=> Fix swapped arguments regression when adding menu

Cargo.lock, Cargo.toml, src/app.rs, src/widget/button.rs, src/widget/contexts.rs, src/widget/core.rs
This PR updates `glazier` and `vello` to the latest versions and syncs `wgpu` and `accesskit` versions. Also `parley` gets an explicit rev to match `glazier`.
~This is dependant on [glazier#72](https://github.com/linebender/glazier/pull/72) which updates `vello` and `wgpu` in `glazier`. I currently used `refs/pull/72/head` to specify the `glazier` version so that this PR here could already be reviewed. Once [glazier#72](https://github.com/linebender/glazier/pull/72) is merged the rev should be changed to a `main` commit.~
The code changes are related to AccessKit. I don't have any testing setup for this so the changes are just my guess. @mwcampbell please take a peek at those changes to see if anything is obviously wrong.
=> Update `glazier`, `vello`, `wgpu`, and `accesskit`.

src/app.rs, src/event.rs, src/lib.rs, src/vec_splice.rs, src/view/any_view.rs, src/view/button.rs, src/view/linear_layout.rs, src/view/list.rs, src/view/mod.rs, src/view/sequence.rs, src/view/view.rs, src/widget/button.rs
This PR adds a `ViewSequence` implementation for `View`, `Option<ViewSequence>`, tupels of ViewSequences and `List`.
To create no conflicts whith the orphan rules, this PR adds the `ViewMarker` trait. It lets the author decide, whether they need to implement `ViewSequence` for their type.
Currently it is not possible to implement a wrapper types like `Adapt` for `ViewSequence`. This would also be possible by adding a second helper trait. Like this:
```rust
trait ViewMarker {}
trait ViewImpl<T, A> {}
trait View<T, A>: ViewImpl<T, A> { ... }
impl<T, A, V> ViewImpl<T, A> for V where V: View<T, A> {}
impl<T, A, V> ViewImpl<T, A> for V where V: ViewSequence<T, A> {}
impl<T, A, V> ViewSequence<T, A> for V where V: View<T, A> + ViewMarker { ... }
```
This way it is not possible to impl View for …
=> Dynamic ViewSequence

README.md
As discussed on the glazier PR, this removes the `x86_64` suffix for the Fedora packages. It also adds some dependencies that I think were missed.
=> Update linux deps

crates/xilem_core/src/any_view.rs, src/view/view.rs
This should make writing boxed Anyviews as type a little bit less convoluted.
Motivation for this was a bigger refactor in [trui](https://github.com/Philipp-M/trui), where the View additionally needed the super trait `Send`. I had a lot of unidentifiable error messages because the `Box<dyn View>` should've been `Box<dyn View + Send>` somewhere in the view-tree (generally a topic that needs some research, to avoid hair-pulling, I think...).
I think adding a type alias that automatically has all these extra trait bounds might be generally helpful.
=> Add a type alias for Box<dyn View> in the anyview macro

crates/xilem_svg/src/kurbo_shape.rs
Since `to_svg` returns a `String`, we don't need to format it to a string.
=> svg: clippy: Fix useless format warnings.

Cargo.lock, crates/xilem_svg/Cargo.toml
There are 2 other crates (so far) with similar naming, but are using the underscore: `xilem_core` and `xilem_html`.
=> svg: Rename `xilemsvg` to `xilem_svg`.

crates/xilem_html/src/view.rs
I don't have a deep understanding of these traits, but this achieves:
- `Either<impl ViewSequence, impl ViewSequence>` implementing `ViewSequence`
- `Either<impl View + ViewMarker, impl View + ViewMarker>` implementing `View` and thus `ViewSequence`
Regarding the new implementation of `ViewSequence`, I have no idea if it's correct, in particular the `rebuild` method. I just implemented it in as closely to the existing `View::rebuild`, and such that the types line up. Please check if I did it right 😅
=> Implement ViewSequence for Either

crates/xilem_core/src/view/memoize.rs
I have skimmed over #65 and saw that the `Clone` trait bound in the `Memoize` view doesn't seem to be necessary (which it indeed isn't).
=> Remove Clone trait bound in Memoize view

src/app.rs, src/app_main.rs, src/widget/button.rs, src/widget/contexts.rs, src/widget/core.rs, src/widget/piet_scene_helpers.rs, src/widget/raw_event.rs, src/widget/text.rs, src/widget/widget.rs
This makes this consistent in terms of where kurbo things are imported from.
=> Import kurbo via vello, not glazier.

crates/xilem_html/src/event/events.rs, crates/xilem_html/src/event/mod.rs, crates/xilem_html/web_examples/todomvc/src/main.rs
Allows adding `.passive(false)` after `.on_click(/* closure */)`. Maybe not the most intuitive but since optional args aren't a thing, I don't have another idea for now.
=> xilem_html: Add support for non-passive event handlers

Cargo.lock, Cargo.toml
Since this is going away in the underlying glazier, we can remove it now to make sure that everyone is aware. The default is `x11`, so this should have little impact.
=> Remove `gtk` feature.

crates/xilem_core/src/view/adapt.rs, crates/xilem_core/src/view/memoize.rs
More readable in documentation, and improves rustfmt's output.
Before:
After:
=> xilem_core: Move bounds to where clauses in macros

crates/xilem_html/src/lib.rs
More macro-generated symbols that were not accessible.
=> xilem_html: Re-export memoize, s functions from crate root

crates/xilem_core/src/view/adapt.rs, crates/xilem_core/src/view/memoize.rs, crates/xilem_html/src/view.rs, crates/xilem_svg/src/view.rs, src/view/view.rs
This PR mostly removes the unnecessary `Send` trait bounds for the `Adapt`, `AdaptState` and `Memoize` views in xilem_html and xilem_svg.
It's split off of #108, as I'm not sure whether to proceed with that PR.
=> Make function trait-bounds of the `Memoize`, `Adapt` and `AdaptState` views configurable (mostly to mirror the `View` trait bounds)

.github/workflows/rust.yml, src/app_main.rs, src/view/mod.rs, src/widget/contexts.rs, src/widget/mod.rs, src/widget/piet_scene_helpers.rs
Currently there are two warnings left, that I think need discussion, like the following:
```
error: module has the same name as its containing module
--> src/view/mod.rs:24:1
|
24 | mod view;
```
I think these are good points, and I have named these `core` in my TUI framework for each of these modules (widget and view), and would suggest doing this as well here.
=> Added `cargo clippy` to the CI workflows and fixed/disabled a few clippy lints

crates/xilem_core/src/message.rs
The match arm is already covered in the arm below (the removed one).
=> xilem_core: Remove redundant macro match arm in message macro

src/app.rs
Small improvements, for more clarity IMHO (and the `.as_mut().unwrap()` seems to be unnecessary, not sure if that was done intentionally).
=> xilem: improve naming and unnecessary function calls in App::render_inner

Cargo.lock, Cargo.toml, src/app_main.rs
Updates xilem to the latest vello. Also bumps wgpu to 0.17.0.
This should enable CFF/CFF2 support.
=> Bump vello (and wgpu versions)

crates/xilem_html/src/element/attribute_value.rs, crates/xilem_html/src/element/attributes.rs, crates/xilem_html/src/element/elements.rs, crates/xilem_html/src/element/mod.rs, crates/xilem_html/src/lib.rs, crates/xilem_html/web_examples/todomvc/src/main.rs
Where \<value\> can be numbers, booleans and strings and options of values.
This is achieved via an enum that serializes to a string and the From trait.
if the attribute is either set to `None` or `false`, the attribute won't be serialized at all (or added to the attributes map at that).
This is slightly less ambitious (and controversial?) than #119 and is used as basis for all attributes there (slightly different implementation, this PR is an improved version without the `BTreeSet` that is used there for classes). 
(This is also ready to merge/review but is built on top of #124 and #125, so those have to be merged/reviewed first).
=> xilem_html: Add support for different types in el.attr("attr", <value>) 

crates/xilem_html/src/element/elements.rs, crates/xilem_html/src/element/mod.rs
I guess I was a little bit too fast with merging the previous PR (not my day today). Minor improvement, replace the unnecessary `impl Into<CowStr>` with `&str`
=> xilem_html: minor improvement in `Element::remove_attr` (use `&str` instead of `Into<CowStr`)

Cargo.lock, Cargo.toml, src/app_main.rs, src/widget/raw_event.rs
This helps pave the way for updating Xilem to use pointer events.
=> Update to current-ish glazier.

.github/workflows/ci.yml
No clippy influenced changes required this time.
=> Bump Rust stable toolchain to 1.73.

src/app.rs
=> Fix panic at Option::unwrap in App::accessibility

Cargo.lock, Cargo.toml, crates/xilem_svg/Cargo.toml, crates/xilem_svg/README.md, crates/xilem_svg/index.html, crates/xilem_svg/src/class.rs, crates/xilem_svg/src/clicked.rs, crates/xilem_svg/src/common_attrs.rs, crates/xilem_svg/src/context.rs, crates/xilem_svg/src/kurbo_shape.rs, crates/xilem_svg/src/lib.rs, crates/xilem_svg/src/pointer.rs, crates/xilem_svg/src/view_ext.rs, crates/xilem_svg/web_examples/svgtoy/Cargo.toml, crates/xilem_svg/web_examples/svgtoy/index.html, crates/xilem_svg/web_examples/svgtoy/src/main.rs
This patch updates the xilem_svg crate to make it suitable for tinkering. The demo app is moved to a separate crate, rather than being hardwired, and the `ViewExt` trait is wired up properly (replacing the previous `KurboShape` hack).
=> Dust off xilem_svg

examples/hello.rs, src/view/text.rs, src/widget/text.rs
Adds a few more string based views, using the existing `TextWidget` widget
=> Add more String views (`&'static str`, `Cow<'static, str>`)

examples/hello.rs, src/view/button.rs, src/view/mod.rs, src/view/text.rs, src/widget/contexts.rs, src/widget/mod.rs, src/widget/text.rs
There was already a text widget in the repository. This PR:
- Enables the text view and widget modules
- Fixes them up so they compile with latest Xilem
- Implements compute_max_intrinsic for text
I'm not sure that having `String` for the view makes sense because:
- Strings are not string literals, so the DX isn't that great anyway as you have to wrap in `String::from`, which is longer than some hypothetical `text` function for a custom text type.
- We're almost certainly going to want modifiers on text like font size, color, etc. And we'll need to store those somewhere.
But I've left it as `String` for now.
=> Enable `Text` widget

.github/workflows/ci.yml
No Clippy influenced changes required this time.
=> Bump Rust stable toolchain to 1.74.

src/widget/core.rs
Previously, this was being overwritten by each widget as the event went up the tree, so only the root widget could be active
This aligns this code with the druid version (see https://github.com/linebender/druid/blob/e53a5ab72c40191b3f92edef9ebf4da07da254f3/druid/src/core.rs#L812)
=> Correctly pass the `HAS_ACTIVE` state up

examples/hello.rs, src/view/mod.rs, src/view/switch.rs, src/widget/button.rs, src/widget/mod.rs, src/widget/piet_scene_helpers.rs, src/widget/switch.rs
=> Switch widget (2nd attempt)

src/widget/core.rs, src/widget/linear_layout.rs, src/widget/switch.rs
I have fixed the visuals of the knob in the hot (bigger and lighter), active (smaller and darker) and idle configuration.
The knob would also jump if the dragging started from the negative area of the widget and it seemed kinda jerky.
I have also disabled some of print statement in other places to cleanup the terminal output
=> Switch widget visual fixes

src/lib.rs, src/widget/mod.rs
Trivial change to allow programs using xilem to share its components, for custom widgets without using a local patch.
=> Export crates/modules to facilitate external widget definitions

crates/xilem_html/src/view.rs
I wanted to use numbers as view directly. I don't see why we shouldn't support that, this adds support for that in xilem_html.
(And it reduces a little bit of the string view boilerplate)
=> xilem_html: Add more text views (support numbers directly as view)

.gitignore, Cargo.lock, Cargo.toml, examples/taffy.rs, src/view/mod.rs, src/view/taffy_layout.rs, src/widget/core.rs, src/widget/mod.rs, src/widget/taffy_layout.rs, src/widget/text.rs, src/widget/widget.rs
Enable Taffy based layout to be used with Xilem
- Gitignore .DS_Store files 
- Add `compute_max_intrinsic` method to `Pod` (this method already existed on the `Widget` trait)
- Add `downcast_ref` method to `Pod` (there was already a `downcast_mut` method)
- Added `cx.request_paint()` in the layout method of the button widget (otherwise it wasn't repainting on window resize)
- Create `TaffyLayout` widget and corresponding view (adapted from the `LinearLayout`). Constructors for the view currently include `flex_row`, `flex_column`, and `div`.
- Create `taffy` example which uses the new view/widget.
- For the most part this could have been implemented as a 3rd party widget. The only changes required outside of creating the view/widget themselves were minor and not taffy-specific.
- ~This is …
=> Implement `TaffyLayout` widget

src/widget/taffy_layout.rs
`TaffyLayout` caches layout based on input dimensions. If a widget in the tree under a `TaffyLayout` requests a layout change, it is only performed on e.g. a subsequent window size change or a tree rebuild.
Note `TaffyLayout` already conditionally clears the cache in the view rebuild, but layout requests made from a child widget currently do not.
Example to reproduce: `TestWidget` renders two rectangles, a green one indicating the currently computed layout, and a yellow one indicating the layout we wish to have. Hovering over the rectangle and scrolling the mouse wheel increases or decreases the widget's desired height. Without this patch, the layout is not recomputed until the window size changes.
```rust
use vello::peniko::{Brush, Color, Stroke};
use xilem::{
view::{View, ViewMarker}, …
```
=> xilem: invalidate `TaffyLayout` cache on child layout request

Cargo.lock
This PR is a simple `cargo update` which thankfully gets us `ahash` v0.7.6 -> v0.8.7 as the 0.7 branch no longer compiles with the nightly toolchain.
=> Fix compilation with nightly toolchain (cargo update)

Cargo.toml, crates/xilem_core/Cargo.toml, crates/xilem_web/Cargo.toml, crates/xilem_web/web_examples/counter/Cargo.toml, crates/xilem_web/web_examples/counter_custom_element/Cargo.toml, crates/xilem_web/web_examples/mathml_svg/Cargo.toml, crates/xilem_web/web_examples/svgtoy/Cargo.toml, crates/xilem_web/web_examples/todomvc/Cargo.toml
As of Rust 1.74, lints can be configured within the `Cargo.toml` which allows us to not have to configure them in the source code as well as simplifying having a single configuration across an entire workspace.
This is documented at: https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-lints-section
=> clippy: Configure via `lints` table in `Cargo.toml`

crates/xilem_core/src/sequence.rs, crates/xilem_core/src/vec_splice.rs, crates/xilem_web/src/elements.rs, src/view/tree_structure_tracking.rs
Fixes #186 
`v` in `VecSplice` can be the original vector, while `ix` is still pointing to the first element, this should fix that. (`peek` and `peek_mut` should point to the current `ix` element)
=> Fix peek in `VecSplice`

crates/xilem_web/src/interfaces.rs
According to the spec, `style` is not available on `Element` itself, but it is on `SVGElement` and `HTMLElement`.
=> xilem_web: Allow `style` only on `HtmlElement` and `SvgElement`

Cargo.lock, Cargo.toml, examples/taffy.rs, src/app.rs, src/text.rs, src/widget/button.rs, src/widget/text.rs
This pulls in a new version of parley with fount replaced by fontique.
=> Update parley dependency to bring in new font fallback support

Cargo.lock, crates/xilem_web/Cargo.toml
This also lets us stop building a separate version of kurbo for xilem_web.
=> [deps] Use release of peniko.

crates/xilem_web/src/class.rs
Should allow `el.class(["class1", "class2"])`, as something like `el.class("class1 class2")` doesn't seem to be allowed (probably worth adding more documentation at some time soon).
=> xilem_web: Support arrays (`impl IntoClasses for [impl IntoClasses; N]`) as classes

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/masonry/Cargo.toml, crates/masonry/examples/calc.rs, crates/masonry/examples/hello.rs, crates/masonry/src/lib.rs, crates/masonry/src/testing/harness.rs, crates/masonry/src/widget/flex.rs, crates/xilem_masonry/Cargo.toml, crates/xilem_masonry/examples/mason.rs, crates/xilem_masonry/src/id.rs, crates/xilem_masonry/src/lib.rs, crates/xilem_masonry/src/sequence.rs, crates/xilem_masonry/src/vec_splice.rs, crates/xilem_masonry/src/view/button.rs, crates/xilem_masonry/src/view/flex.rs, crates/xilem_masonry/src/view/mod.rs
Alternative to #204
Demonstrates a viable path forward to Xilem. This does not get rid of the widget set in the main Xilem crate, or migrate the main Xilem crate to this
=> Create a minimal xilem_masonry

Cargo.lock, Cargo.toml, crates/masonry/Cargo.toml
This will help us keep everyone using the same version. This also makes both `xilem` and `masonry` use the same version now.
=> parley: Use via workspace dependency.

crates/masonry/.cargo/config.toml, crates/masonry/Cargo.toml
This replaces the old lint configuration in a cargo config with the workspace lint configuration in the Cargo.toml.
The old lint configuration was for tests, which don't currently trigger those lints, so we don't need to supply this configuration elsewhere. (The library has its own lint configuration that supplements this in `src/lib.rs` which can be improved later.)
=> masonry: Use workspace lint config.

crates/masonry/Cargo.toml
This is generating a warning every time you build about it being here and that it will be ignored:
```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /.../xilem/crates/masonry/Cargo.toml
workspace: /.../xilem/Cargo.toml
```
=> masonry: Remove profile from non-root Cargo.toml.

Cargo.lock, Cargo.toml
This version of parley has fontique as a separate crate and has updated dependencies (as well as a removal of clap as a transitive dep).
=> deps: Update parley.

crates/xilem_masonry/src/any_view.rs
Previously, this meant that the previous was actually a `Box<dyn AnyView>`, which implemented `View` and so was being passed as its own `&dyn AnyView` to rebuild.
I also moved `rebuild` and `message` into the correct order.
This partially fixes the `mason` example - pressing the `Unlimited Power` button, it now retains its state.
This would be more impactful for e.g. a text input view, where the widget had internal state.
Pressing activate and deactivate is still broken. See [#masonry > Hot state for new widgets](https://xi.zulipchat.com/#narrow/stream/317477-masonry/topic/Hot.20state.20for.20new.20widgets)
=> Properly `deref` the previous view when using `AnyMasonryView`

crates/xilem_masonry/examples/mason.rs, crates/xilem_masonry/src/any_view.rs, crates/xilem_masonry/src/id.rs, crates/xilem_masonry/src/lib.rs, crates/xilem_masonry/src/sequence.rs, crates/xilem_masonry/src/view/button.rs, crates/xilem_masonry/src/view/flex.rs
Alternative to #218
The version of viewsequence added in #205 is robust for all properties supported in that version. However, it would be incompatible with future expansions to the Xilem model, in particular async wiring.
In this PR, I propose a system to resolve this, which uses generational indexes in the view id path (for the items where this is relevant).
Some other historical record: #9
This brings back the `View::State` associated type (renamed to `ViewState` and `SeqState` depending on the trait), in order to perform this wiring.
=> xilem_masonry: Robust generational indexing for `ViewSequence`

crates/xilem_web/src/vecmap.rs
Define generic bounds once rather than partly in the bound predicate and partly in the `where` clause.
=> xilem_web: Fix clippy::multiple_bound_locations lints.

crates/xilem_masonry/examples/mason.rs, crates/xilem_masonry/src/view/button.rs, crates/xilem_masonry/src/view/checkbox.rs, crates/xilem_masonry/src/view/mod.rs
Implements the masonry checkbox as view (and some improvements in `Button::message`)
=> xilem_masonry: Add checkbox widget

crates/masonry/src/lib.rs, crates/masonry/src/widget/flex.rs, crates/masonry/src/widget/label.rs, crates/xilem_masonry/examples/mason.rs, crates/xilem_masonry/src/lib.rs, crates/xilem_masonry/src/view/flex.rs, crates/xilem_masonry/src/view/label.rs, crates/xilem_masonry/src/view/mod.rs
Adds the label widget to `xilem_masonry` with some (but not all) attribute setters, and methods to disable the label in masonry.
Also slightly extends the `Flex` view, by being able to specify the direction (and a small fix in `FlexSplice`).
=> xilem_masonry: Add Label widget

Cargo.lock, Cargo.toml
We don't need to force the usage of 0.5.0.
=> deps: Use `raw-window-handle` 0.6.0

crates/masonry/src/event.rs, crates/masonry/src/render_root.rs, crates/masonry/src/widget/tests/snapshots/masonry__widget__tests__lifecycle_basic__app_creation.snap, crates/masonry/src/widget/widget_pod.rs
The exact circumstances in which ParentWindowOrigin need to be sent aren't entirely clear to me so this might need some more careful thought
This does resolve [#masonry > Hot state for new widgets](https://xi.zulipchat.com/#narrow/stream/317477-masonry/topic/Hot.20state.20for.20new.20widgets)
This can be tested in the `mason` example, for example when pressing the `activate` button
=> Update the hot state in `ParentWindowOrigin` as well

crates/masonry/src/lib.rs
I try to use masonry to implement my own application, which requires vello and parley
=> re-export parley && vello

Cargo.lock, Cargo.toml
`xilem` now uses the same `vello` as others (git for now) and everyone uses the new released version of `parley`.
=> deps: Use workspace vello, release parley.

crates/masonry/src/widget/button.rs
This matches the behaviour in Xilem classic
=> Masonry: Only activate buttons when they are hot

crates/masonry/src/widget/button.rs
When pressing the button and releasing it outside of its active area, the visual pressed state (background gradient) stays "pressed". This should fix this.
(Not related to that PR) I'm not sure, if there's a case, where the disabled state could change while pressing the button and trigger a similar behavior.
=> masonry: Fix non-resetting visual active state when releasing active button outside of its area

crates/masonry/src/contexts.rs, crates/masonry/src/event.rs, crates/masonry/src/event_loop_runner.rs, crates/masonry/src/render_root.rs, crates/masonry/src/testing/harness.rs, crates/masonry/src/widget/split.rs, crates/masonry/src/widget/widget_pod.rs, src/app_main.rs, src/widget/raw_event.rs
Generally prefer use of LogicalPosition to PhysicalPosition for layout, events, etc. Use scale factor to convert to logical position. Apply scale factor as final transform before Vello rendering.
This PR also makes physical_position available in PointerState.
There is a TODO for handling WindowEvent::Rescale, which remains and is not addressed. It should be at some future point.
=> Wire up scale factor

Cargo.lock, Cargo.toml
As discussed at office hours we're going with Vello v0.1.0 for now, as using the git dependency blocks publishing and Vello 0.2 isn't ready.
=> Revert to `vello` v0.1.0.

Cargo.lock, Cargo.toml, crates/masonry/Cargo.toml, crates/xilem_core/Cargo.toml, crates/xilem_masonry/Cargo.toml, crates/xilem_masonry/examples/mason.rs, crates/xilem_web/Cargo.toml, examples/hello_xilem.rs, examples/taffy.rs
* Rename classic `xilem` to `xilem_classic` and the new `xilem_masonry` to `xilem`.
No directory structure changes yet to avoid merge conflicts before RustNL.
* Base common dependencies on workspace dependencies.
* Bump `masonry` version to `0.2.0`.
* Remove some legacy docs.rs configuration inherited from Druid/Glazier that is no longer needed.
* Unify ordering of properties.
=> Prepare `Cargo.toml` files for release.

crates/xilem_masonry/src/any_view.rs
This fixes the problem where the container widget had the same role as its child, leading to, for example, nested buttons in the mason example.
=> Return the correct accessibility role in DynWidget

crates/masonry/examples/calc.rs, crates/masonry/src/widget/button.rs, crates/masonry/src/widget/checkbox.rs, crates/masonry/src/widget/flex.rs, crates/masonry/src/widget/label.rs, crates/masonry/src/widget/prose.rs, crates/masonry/src/widget/textbox.rs, crates/masonry/src/widget/widget_ref.rs, crates/xilem_masonry/src/view/button.rs, crates/xilem_masonry/src/view/label.rs, crates/xilem_masonry/src/view/prose.rs, crates/xilem_masonry/src/view/textbox.rs
This is fallout from #241. As discussed on Zulip, using different underlying text types here is a very advanced feature, which will not be needed by any real consumers. It also creates some footguns
Probably conflicts with #257, so that should land first
=> Cleanup the text widgets to not be generic

crates/masonry/src/text_helpers.rs
Previously, we were rendering the first line `n` times, the second line `n-1` times, etc.
(Because the copy was in the loop)
See [#xilem > ✔ Text rendering when using nested Scenes](https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/.E2.9C.94.20Text.20rendering.20when.20using.20nested.20Scenes)
=> Unbreak text rendering

crates/xilem_masonry/src/view/flex.rs
While adding filters to the TodoMVC example, I produced a crash. Which seems to originate because there was a spacer added, which also increments the underlying element child count.
So in case we want to have that spacer, we need to increment by 2 instead...
(Since `mutate` and `delete` skip spacers, because `child_mut` returns none, and the index is only incremented for concrete children it's not necessary to change the index incrementation code there)
=> xilem_masonry: Fix Flex splice (increment ix by 2 because of spacer widget)

crates/xilem_masonry/README.md
This is a basic skeleton based on the latest Linebender standards.
I also added a paragraph about the reactive layer's origins.
Plus a section describing the modularity of our stack.
Additional sections describing more of the actual new state of things are welcome in follow-up PRs, but are not a goal of this PR.
=> Add `README.md` for `xilem`.

crates/masonry/src/text_helpers.rs
This will be needed to follow on from #273 (showing the pre-edit region visually)
and
cc @dfrg for awareness, I'm not certain on the maths (but that doesn't need to block merging)
=> Implement underlining and strikethrough for Masonry

crates/masonry/src/contexts.rs
Fixes the issue described in #265.
I *think* this is the proper fix, it seems to be similar as in previous xilem (where I think that pass is called `ViewContextChanged`).
=> masonry: Require `ParentWindowOrigin` lifecycle when origin of child has changed

crates/masonry/src/widget/textbox.rs
Previously, filling up the line would overflow the right border of the box, because the `max_advance` was too big.
This improves the margin hack, and also fixes the resultant issue.
=> Fix the handling of textbox width

Cargo.lock, Cargo.toml, crates/masonry/Cargo.toml
The `image` crate has a number of dependencies which aren't needed in the core masonry crate, so we can turn off the default image format support and only enable "png" when used as a dev dependency.
Also, make it a workspace dependency at the same time so that the version is only stated in a single location.
=> deps: Update `image`, make workspace, turn off default features.

crates/masonry/src/widget/textbox.rs
Previously, click-and-drag selection in the textbox would select the wrong characters (among other issues with clicking)
=> Fix incorrect handling of the margin in textbox selection

crates/xilem_masonry/src/view/label.rs
We should be following the system theme here, probably.
And doing a lot of other things. But this is a saner default with a black default "background"
=> Make the default label colour white

crates/masonry/src/lib.rs
Having this denied means we can't generate docs locally. We can re-enable this once the issues are fixed.
=> masonry: docs: Don't `deny(rustdoc::broken_intra_doc_links)`.

Cargo.toml
Previously, this depended only on version `0.3`, which had a advisory issued for it.
=> xilem_classic: deps: Require current `futures-task`

Cargo.lock, crates/xilem_web/Cargo.toml
This is always used via `peniko`.
=> xilem_web: Remove unused direct dep on `kurbo`.

crates/xilem_web/src/style.rs, crates/xilem_web/web_examples/mathml_svg/src/main.rs
Fixes #295
Also implements `IntoStyles` for `[impl IntoStyles; N]`
=> xilem_web: Fix mathml example (use `style` method instead of untyped `attr`)

crates/xilem_masonry/examples/flex.rs, crates/xilem_masonry/src/view/flex.rs
Wired up some more existing masonry flex properties so they can be set on the flex view.
I was messing around with a dummy example to try out the v0.1 and noticed I couldn't easily center something because flex was only exposing direction not alignment/cross-alignment. It looked like all the logic already exists in masonry so it was just a matter of wiring it up. This is my first contribution so sorry if I missed some steps.
Sidenote: I didn't see any examples of testing that a view updates the underlying element so I am guessing that is still tbd. If someone has a suggestion for a good way to do that I am happy to try it out.
I'm also not sure what the etiquette is on adding/editing examples so I just included the example I was using to verify it worked but no stress if you want to …
=> Additional flex view options

crates/masonry/src/text2/edit.rs
Doing some investigation, the issues I'm seeing is that ibus is a bit/a lot broken around compose keys
But this has correct behaviour for me. This matches the documentation of the `winit` [`Ime`](https://docs.rs/winit/latest/winit/event/enum.Ime.html) event.
=> Handle IME in a way which winit expects

Cargo.lock, masonry/Cargo.toml, masonry/src/contexts.rs, masonry/src/lib.rs, masonry/src/render_root.rs, masonry/src/widget/mod.rs, masonry/src/widget/prose.rs, masonry/src/widget/split.rs, masonry/src/widget/textbox.rs, masonry/src/widget/widget_state.rs
`cursor_icon` is a crate that is used by `winit` to provide its `CursorIcon` type separately from the `winit` crate.
This re-exports the `CursorIcon` from `masonry` and then uses that rather than via `winit::window::CursorIcon`, allowing the use of the `CursorIcon` without having to independently discover its provenance.
This is also one step towards not requiring `winit` within the `masonry` internals apart from the actual window / event loop management.
=> `masonry`: Use `cursor_icon` crate directly.

xilem_web/web_examples/counter/index.html, xilem_web/web_examples/counter_custom_element/index.html, xilem_web/web_examples/mathml_svg/index.html, xilem_web/web_examples/svgtoy/index.html
For some reason the recent version of Trunk refused to serve some of the examples due to them missing the <html> tags. Adding the tags calms it down and allows it to work again. Trivial change, but would save someone the pain of having to fix examples before running them with trunk serve.
=> fix invalid HTML in examples

masonry/src/event_loop_runner.rs
They are unused (and rarely useful), and they cause unwanted behavior.
=> Ignore synthetic keyinput events for now

docs/assets/xilem-architecture.svg
The architecture diagram is very hard to read on the dark theme of github
=> Update xilem-architecture.svg to have a white background

.github/workflows/ci.yml, .typos.toml
Currently, the only legit typo being found is `seeked` but I'm not sure what to do about that.
Would be nice to check for new typos in CI anyways, right?
=> Check for typos in CI

xilem/examples/memoization.rs, xilem/src/any_view.rs, xilem/src/lib.rs, xilem/src/view/arc.rs, xilem/src/view/button.rs, xilem/src/view/checkbox.rs, xilem/src/view/flex.rs, xilem/src/view/memoize.rs, xilem/src/view/mod.rs, xilem/src/view/textbox.rs
This ports the `Memoize` view from old xilem, slightly enhances it, by checking whether the given view callback is a non-capturing closure and not a function pointer (by asserting `std::mem::size_of::<F>() == 0`)
It also ports the `Arc<impl View>` and `Arc<dyn AnyMasonryView>` from #164 including the example there to show how these two forms of memoization can be used.
=> xilem: Add Memoization views (`Memoize` and `Arc<impl View>`)

Cargo.lock, Cargo.toml, masonry/Cargo.toml, masonry/examples/calc.rs, masonry/examples/hello_masonry.rs, masonry/examples/simple_image.rs, masonry/src/contexts.rs, masonry/src/event.rs, masonry/src/event_loop_runner.rs, masonry/src/lib.rs, masonry/src/render_root.rs, masonry/src/testing/harness.rs, masonry/src/widget/split.rs, masonry/src/widget/widget_pod.rs, xilem/src/lib.rs
This removes a class of dependencies from within both `masonry` and `xilem` on the `winit` crate where we can just use `dpi` directly instead.
The `dpi` crate is meant (like `cursor_icon`) to be a shared ecosystem crate rather than only for usage with `winit`.
=> xilem,masonry: Use `dpi` crate directly

Cargo.toml
The current nightly issues warnings for unknown cfgs, so we need to suppress some of these for now.
Even though these are only needed for `masonry`, we put them in the workspace configuration due to limitations in how the lints table is configured and overridden in current versions of Cargo.
=> lints: Suppress some check-cfg warnings

masonry/doc/ARCHITECTURE.md, masonry/src/event_loop_runner.rs, masonry/src/render_root.rs, masonry/src/testing/harness.rs, masonry/src/widget/align.rs, masonry/src/widget/button.rs, masonry/src/widget/checkbox.rs, masonry/src/widget/flex.rs, masonry/src/widget/image.rs, masonry/src/widget/label.rs, masonry/src/widget/mod.rs, masonry/src/widget/portal.rs, masonry/src/widget/prose.rs, masonry/src/widget/scroll_bar.rs, masonry/src/widget/sized_box.rs, masonry/src/widget/spinner.rs, masonry/src/widget/split.rs, masonry/src/widget/textbox.rs, masonry/src/widget/widget_pod.rs, masonry/src/widget/widget_ref.rs
[VS Code marker comments](https://code.visualstudio.com/docs/editor/custom-layout#_minimap-and-breadcrumbs) are a [new feature](https://code.visualstudio.com/updates/v1_88#_minimap-section-headers) that supposedly help with browsing the code with a minimap. I don't know if other editors have equivalents.
I haven't tested them before, and I don't know whether they actually improve DX, but they're pretty simple and unobstrusive, so I think it'd be worth adding them experimentally and seeing how it goes.
=> Add VS Code marker comments to code

masonry/src/app_driver.rs, masonry/src/lib.rs
This allows for running `masonry` with an externally managed event loop for integrating with an application that is already running an event loop.
* Expose `PointerState` to allow creating `PointerEvent`
* Expose `WindowEvent` to allow managing window size and scale factor.
* Make `DriverCtx` usable from outside the crate. While this struct was already `pub`, the sole member of it was not.
=> Allow feeding masonry from an externally event loop.

Cargo.lock, Cargo.toml, masonry/Cargo.toml, masonry/src/render_root.rs, masonry/src/widget/spinner.rs
Recently, `instant` has been marked as unmaintained by the maintainer. A suggested replacement is `web-time`, which is used by `winit` and is already in our dependency tree.
=> masonry: Use `web-time` instead of `instant`

masonry/src/event_loop_runner.rs
This helps make it more clear when skimming through this code that this is the scale factor being used to transform the scene.
=> masonry: Rename a scale factor variable

Cargo.lock
This bumps the `accesskit_consumer` version in `Cargo.lock` to the next minor version (`0.19.1`).
That version includes better error messages when AccessKit panics.
=> Bump accesskit sub-dependency version

Cargo.toml
Enabling [`assigning_clones`](https://rust-lang.github.io/rust-clippy/master/index.html#/assigning_clones) by default in Rust 1.78 was a mistake which was reversed in a week in [rust-clippy#12779](https://github.com/rust-lang/rust-clippy/pull/12779).
We can disable it locally until the upstream fix arrives to stable Rust.
=> Disable `clippy::assigning_clones` lint.

masonry/src/event.rs, masonry/src/event_loop_runner.rs, masonry/src/testing/harness.rs, masonry/src/text2/edit.rs, masonry/src/text2/selection.rs, masonry/src/widget/scroll_bar.rs, masonry/src/widget/split.rs, masonry/src/widget/tests/status_change.rs
This brings the `PointerButton` enum from glazier and has all code outside of the winit event loop integration using it.
For now, it has a `todo!()` for the `MouseButton::Other` as it isn't clear what that is for.
=> masonry: Use own `PointerButton` enum

Cargo.lock, Cargo.toml, masonry/src/event_loop_runner.rs, masonry/src/testing/harness.rs
This brings us to the 0.2 release of Vello, which brings the 0.20 release of wgpu.
=> deps: Update `wgpu`, `vello`, `peniko`

masonry/src/event_loop_runner.rs
In #254, we had an initial log format added.
However, that doesn't include support for milliseconds, which are useful in a GUI system because it allows getting a first approximation of latency. I'm adding this now because of the startup latency issues first observed in #381 ([#masonry > Slight Startup Time Regression](https://xi.zulipchat.com/#narrow/stream/317477-masonry/topic/Slight.20Startup.20Time.20Regression))
=> Add milliseconds in the tracing formatting

xilem/src/driver.rs, xilem/src/lib.rs, xilem_core/src/views/memoize.rs, xilem_core/tests/any_view.rs, xilem_core/tests/arc.rs, xilem_core/tests/base_sequence.rs, xilem_core/tests/common/mod.rs, xilem_core/tests/tuple_sequence.rs, xilem_core/tests/vec_sequence.rs
This was brought up in [#xilem > paper cuts](https://xi.zulipchat.com/#narrow/stream/354396-xilem/topic/paper.20cuts)
The memoize change was a copy-and-paste failure
=> Consistently use `ctx` over `cx` in Xilem

Cargo.toml, masonry/README.md, masonry/examples/hello_masonry.rs, masonry/examples/to_do_list.rs, masonry/src/action.rs, masonry/src/lib.rs, masonry/src/testing/harness.rs, masonry/src/widget/button.rs, xilem/examples/mason.rs, xilem/src/view/button.rs
In most cases, you want a button which only actuates when the primary mouse button is pressed, so the easy case is still that. This is a short term hack, because e.g. the active state is still based on any button being pressed, not just those we are interested in.
That is, we probably need to represent a set of buttons we are interested in. However, this change minimally unblocks additional work with Xilem. In particular, see [#xilem > Minesweeper converted from Iced to Xilem](https://xi.zulipchat.com/#narrow/stream/354396-xilem/topic/Minesweeper.20converted.20from.20Iced.20to.20Xilem).
=> Differentiate pointer buttons in `Button` Widget and View

masonry/src/widget/sized_box.rs, xilem/examples/flex.rs, xilem/src/view/mod.rs, xilem/src/view/sized_box.rs
I have chosen not to set the background and border properties, as those are moreso styling properties - in our current state, we seem to be much preferring only specifying layout values
=> Create a `View` for `SizedBox`

Cargo.lock, Cargo.toml
A fix was in winit 0.30.1 to fix a crash on exit on macOS (among other things).
Fixes #239.
=> Update to winit 0.30.2

masonry/examples/custom_widget.rs, masonry/src/contexts.rs, masonry/src/render_root.rs, masonry/src/text2/edit.rs, masonry/src/text2/layout.rs, masonry/src/text2/selection.rs, masonry/src/widget/label.rs, masonry/src/widget/prose.rs, masonry/src/widget/textbox.rs
Based on a suggestion from @dfrg.
This appears to have improved performance with the 30_000 hello's example from ~$\frac{1}{20}$ms to $\frac{1}{160}$ms
So an approx 8x increase in throughput for that scene.
=> Move to a single global `parley::LayoutContext`

xilem/examples/components.rs, xilem/examples/elm.rs, xilem_core/src/lib.rs, xilem_core/src/message.rs, xilem_core/src/views/adapt.rs, xilem_core/src/views/map_action.rs, xilem_core/src/views/map_state.rs, xilem_core/src/views/mod.rs
Ports `Adapt` to new xilem_core.
It also adds `MapState` which was previously called `AdaptState` and a new view `MapAction` which is basically about how elm works.
`MapAction` and `Adapt` is shown in action in the added `elm` example, while `MapState` can be seen in action in the added `components` example.
=> Port `Adapt` from old `xilem_core`

xilem_core/README.md, xilem_core/src/any_view.rs, xilem_core/src/message.rs, xilem_core/src/sequence.rs, xilem_core/src/view.rs, xilem_core/src/views/adapt.rs, xilem_core/src/views/map_action.rs, xilem_core/src/views/map_state.rs, xilem_core/src/views/memoize.rs, xilem_core/src/views/one_of.rs
This adds yet another generic parameter `Message` to the `View`, `ViewSequence` and `AnyView` trait, such that implementors have more freedom about what the message is. This is necessary for xilem_web, as a `Send` bound is not possible to use with wasm_bindgen IIRC. (At least I had to remove it in the `DynMessage` to get it to compile...).
It was fortunately straight-forward to just add the `Message` param with the default `DynMessage`. Basically search replace... (I hope I haven't missed anything, but I went through it twice...)
=> xilem_core: Support generic `Message`s

xilem_core/src/sequence.rs, xilem_core/tests/array_sequence.rs
Adds the blanket impl
`impl<const N: usize, VT: ViewSequence> ViewSequence for [VT; N]`
Allows for example something like this:
```rust
fn my_tab(impl View) -> impl View {..}
h_stack(["Tab 1", "Tab 2", "Tab 3"].map(my_tab))
```
=> Support arrays (`[impl ViewSequence; N]`) as `ViewSequence`s

masonry/src/event.rs, masonry/src/text2/edit.rs
Since #314, we request the IME to be positioned every paint cycle. This triggers a new event from the IME, which is a preedit clear. This IME event also breaks text selection, which is why we handle it here.
This is still not the fully correct behaviour, but it does at least make text selection in textboxes work again. We really need to improve our testing story here.
Also give more detail in the short form of IME events; these events all have quite different properties.
=> Handle an empty preedit

Cargo.lock, xilem_core/Cargo.toml, xilem_core/src/lib.rs, xilem_core/src/views/mod.rs, xilem_core/src/views/orphan.rs, xilem_core/tests/orphan.rs
Since we're suffering from the orphan rule with the new xilem_core implementation, we cannot use `View` in downstream crates for external types such as a `WidgetView` implementation for `&'static str` in Xilem. 
This PR adds an `OrphanView` trait which the `Context` of the `View` has to implement for the type which has an implementation in xilem_core for this. The `View` impl for these types is basically a proxy for `OrphanView` (which in turn has the same method signature as `View`), so downstream crates can achieve the same as with the `View`.
=> xilem_core: Provide a way to add `View` implementations for external types

masonry/doc/ARCHITECTURE.md, masonry/doc/ROADMAP.md, masonry/src/action.rs, masonry/src/box_constraints.rs, masonry/src/contexts.rs, masonry/src/event.rs, masonry/src/testing/snapshot_utils.rs, masonry/src/widget/align.rs, masonry/src/widget/portal.rs, masonry/src/widget/spinner.rs, masonry/src/widget/widget.rs, masonry/src/widget/widget_pod.rs, masonry/src/widget/widget_state.rs
Since we merged https://github.com/linebender/masonry into this repository, these issue numbers were out-of-date.
I found these by search for `#[0-9]`, and got the updated links using `https://github.com/linebender/masonry/issues/{x}`
=> Fix the mentions of Masonry issues to use issue links

masonry/src/text2/layout.rs, masonry/src/widget/label.rs, masonry/src/widget/prose.rs, xilem/examples/flex.rs, xilem/examples/mason.rs, xilem/src/view/label.rs, xilem/src/view/prose.rs
Format:
```rust
label("everything").text_size(42.)
```
and the same with `prose`.
I've also added `font_size` aliases for these, because people will expect it to have these names.
=> Support `text_size` in `Label`/`Prose` views

.github/workflows/ci.yml, .typos.toml, Cargo.toml, masonry/README.md, xilem/README.md, xilem_core/README.md
This was most recently updated in https://github.com/linebender/vello/pull/505
The main differences are:
1) Greater concurrency between clippy and testing
2) More explanations
3) MSRV checking
4) Use of `cargo hack`
5) WASM checked in CI
I've also added the current values of our MSRVs to the main three crates.
=> Update to our latest CI standard

masonry/src/text2/selection.rs
I had trouble getting masonry to compile for iOS due to a winit platform method call that's not supported. There's already a cfg for android so I just added iOS to it.
Reproduction:
```
cargo check --target aarch64-apple-ios
```
=> Remove key_without_modifiers call on iOS

masonry/src/event_loop_runner.rs
As I understand it, on iOS the outer_size corresponds to the size of the window, meaning when the surface is rendered using inner_size(the safe/non-obscured size) the elements get stretched.
There's an open issue in winit about clarifying/standardizing the different sizes, but until that's done switching to outer_size fixes the issue.
The touch positions now also match the rendering
Winit issue: https://github.com/rust-windowing/winit/issues/2308
Fixes #419
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> Use window.outer_size on iOS

Cargo.toml, masonry/src/lib.rs, masonry/src/widget/widget.rs, xilem/examples/mason.rs
Related to #44
We don't have any necessary unsafe code, and I don't think any of us want to lose that.
(Vello is also no longer laundering the unsafety wrt surface creation thanks to a recent wgpu release)
=> Deny unsafe code globally

masonry/src/event_loop_runner.rs, xilem/examples/external_event_loop.rs, xilem/src/lib.rs
These changes allow you to create a masonry or xilem app that is driven by an external event loop.
Existing method for creating masonry app:
```
masonry::event_loop_runner::run(
masonry::event_loop_runner::EventLoop::with_user_event(),
window_attributes,
root_widget,
app_driver,
)
.unwrap();
```
Instead you can now do this:
```
let masonry_state = MasonryState::new(window_attributes, &event_loop, root_widget);
let mut app = AppInterface {
masonry_state,
app_driver: Box::new(driver),
};
event_loop.run_app(&mut app)
```
Where AppInterface implements the winit ApplicationHandler<accesskit_winit::Event> trait.
Existing method:
```
let app = Xilem::new(state, app_logic);
app.run_windowed(EventLoop::with_user_event(), title)?;
```
Now:
```
let xilem = Xilem::new(0, app_logic);
let (root_widget, …
```
=> Allow external event loop to drive masonry and xilem

Cargo.lock, Cargo.toml, xilem_web/web_examples/elm/Cargo.toml, xilem_web/web_examples/elm/index.html, xilem_web/web_examples/elm/src/main.rs
I have intentionally left out the `xilem_core::adapt` variant here in order to have a clear classic Elm example. I would rather show the `adapt` variant in a separate example.
=> xilem_web: Add Elm Architecture example

Cargo.lock, Cargo.toml, masonry/src/widget/label.rs, masonry/src/widget/prose.rs
There was a breaking change in this release that renamed `role::StaticText` to `role::Label`.
=> [masonry] Update to accesskit 0.16

xilem_core/src/views/mod.rs, xilem_core/src/views/one_of.rs, xilem_core/tests/one_of.rs, xilem_web/src/one_of.rs
This still needs to be implemented in Xilem.
But I think this is an improvement overall
=> Change the `OneOf` views to not use macros

masonry/examples/calc.rs, masonry/src/widget/flex.rs, xilem/src/view/flex.rs
See https://developer.mozilla.org/en-US/docs/Web/CSS/gap
Since #428, we no longer have default spacing between flex elements in Masonry. This makes the examples quite ugly.
Choices made based on [#xilem > Porting Taffy Integration to New Xilem](https://xi.zulipchat.com/#narrow/stream/354396-xilem/topic/Porting.20Taffy.20Integration.20to.20New.20Xilem). Of particular note is the choice to not have this be overwritten by spacers, due to:
> My first thought is that users are going to be very confused when they add a space between two items and the result is the items are closer together.
There is no such concept of a spacer in CSS parlance
=> Add a CSS `gap` inspired Flex property.

README.md, masonry/Cargo.toml, xilem/Cargo.toml, xilem_core/Cargo.toml, xilem_web/Cargo.toml, xilem_web/README.md
Discovered in #432; this would otherwise cause errors for users of nightly (or 1.81 beta, due to be released next week)
=> Correctly set `rust-version` in all `Cargo.toml`s

masonry/src/event_loop_runner.rs, xilem/examples/external_event_loop.rs, xilem/examples/mason.rs, xilem/src/lib.rs
Adds `Xilem::background_color` builder method and the relevant changes to Masonry. I've also modified `mason` example to demonstrate the usage of the new API. 
[Zulip discussion](https://xi.zulipchat.com/#narrow/stream/354396-xilem/topic/Window.20background.20color)
=> Expose control over window background color

xilem_web/src/interfaces.rs
Fixes #446 
I guess I missed the m before the path
=> xilem_web: Support `Fill` for `SvgPathElement` instead of `SvgmPathElement`

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, masonry/Cargo.toml, masonry/src/testing/harness.rs, xilem/Cargo.toml, xilem_core/examples/filesystem.rs, xilem_web/web_examples/todomvc/Cargo.toml
There is one "semi-false-positive" lint triggered, which I have fixed.
Otherwise, the required
```
cargo upgrade --ignore-rust-version
cargo update
```
=> Update dependencies and bump to Rust 1.80

xilem_web/src/events.rs
I think we could also create some additional sugar around that, but since the event is given to the user, they can handle that behavior anyway.
Fixes #457
=> xilem_web: Remove hardcoded `prevent_default`/`stop_propagation` as the user should decide that behavior

xilem_web/src/lib.rs
I guess I missed this when adding #408, the doc-test should ensure that `Box<AnyDomView>` is now really a `DomView`.
=> xilem_web: Fix message type of `AnyDomView` and add `.boxed()` combinator

xilem_web/src/lib.rs
=> xilem_web: Fix #465, by actually replacing the old element in the DOM-tree

xilem/examples/memoization.rs, xilem/src/view/mod.rs, xilem_core/src/lib.rs, xilem_core/src/view.rs, xilem_core/src/views/memoize.rs, xilem_core/src/views/mod.rs, xilem_core/tests/arc.rs
This adds a `force` which is basically a specialized `Memoize` without any bound data.
This also cleans up `Memoize` a little bit (mostly code-aesthetic stuff, but also adds `State` and `Action` params to the view, so that it doesn't offer weird surprises when composing it with views like `Adapt`).
The `Arc` view is also fixed, as it didn't support force rebuilding yet, which is relevant for e.g. async, e.g. the `MemoizedAwait` view would not work inside an `Arc<impl View>` currently.
=> xilem_core: Refactor Memoization (add `Frozen` view, fix force-rebuild in `Arc`, and cleanup `Memoize`)

xilem_web/src/interfaces.rs
From manually testing in Chrome, values between `2**31` and `2**31 - 1` work, so this takes an `i32`.
It's pretty trivial code, but I think it would be really nice to add some kind of test, or even just an example which uses it.
What do you think about adding a "misc" example for `xilem_web`, which exercises a bunch of small features? I was thinking a layout with a column on the left with a list of items with a larger area on the right.  When an item on the left is clicked, the right side is populated with whatever that item is.
In this case, the item name would be `ol-li-value`, which when clicked would show something like this on the right:
```rust
ol((
li("foo"),
li("bar"),
li("baz").value(10),
li("qux"),
));
```
Ideally, this would be compiled as part of CI, to make sure that no …
=> xilem_web: Add HtmlLiElement `value` attribute setter

masonry/src/testing/harness.rs, masonry/src/text/backspace.rs, masonry/src/text/edit.rs, masonry/src/text/selection.rs, masonry/src/tree_arena.rs, masonry/src/widget/widget.rs
=> Fix some `clippy::doc_markdown` lints in masonry.

masonry/src/text/edit.rs
`masonry::text::edit::TextEditor` should emit an `Action::TextChanged(...)` also on `Backspace` and `Delete` if anything was deleted, so that e.g. `xilem::view::textbox::Textbox` receives this action. This is already implemented for `Ctrl+Backspace` and `Ctrl+Delete`.
The code changes are not elegant, but intended to be minimally invasive.
Local `cargo test` failed for the modified and an unmodified code, but sometimes with different errors&mdash;which I do not quite understand.
I apologize in advance for any mistakes on my part, I've never before worked on open source repos and did not find any guideline for your project.
=> masonry: `TextEditor` add `Action::TextChanged` for backspace & delete

xilem_web/Cargo.toml, xilem_web/src/context.rs, xilem_web/src/elements.rs
I'm surprised that this was not noticed yet, `DomChildrenSplice::with_scratch` previously only appended new elements to the end of the children of an element in the DOM tree, whereas it should've inserted it at the current index of the `ElementSplice`. This should fix this, using a `DocumentFragment` which is shared on the `ViewCtx` to avoid unnecessary allocations.
=> xilem_web: Fix `DomChildrenSplice::with_scratch`

xilem/examples/calc.rs, xilem_web/web_examples/mathml_svg/src/main.rs
Reduces a little bit of the boilerplate in `calc`
=> Improve `calc` and xilem_web's `mathml_svg` example

xilem_web/src/app.rs, xilem_web/web_examples/counter/src/main.rs
Should fix #461. This allows a `ViewSequence` (called `DomFragment`) of `DomView`s as root component.
The `counter` example is updated to show this new behavior.
=> xilem_web: Allow `DomFragment` instead of `DomView` as `app_logic`

xilem_web/src/concurrent/interval.rs, xilem_web/src/concurrent/mod.rs
Simple but convenient `View`, e.g. for some kind of ticker. (Maybe needs an additional example)
=> xilem_web: Add `interval` `View`, which somewhat reflects `setInterval`

xilem/examples/calc.rs
=> xilem: Fix calc example (missing `flex` property)

xilem_web/src/events.rs, xilem_web/src/svg/common_attrs.rs, xilem_web/web_examples/svgtoy/src/main.rs
Uses `ViewState` for a little bit of optimization (of allocations mostly).
=> xilem_web: Add support for opacity in `svg::Fill` and dashes, opacity in `svg::Stroke`

masonry/src/event_loop_runner.rs, masonry/src/widget/mod.rs, masonry/src/widget/spinner.rs, xilem/examples/state_machine.rs, xilem/src/view/mod.rs, xilem/src/view/spinner.rs
This is the smallest change possible to make animations work in Masonry.
Essentially, we treat every redraw as a potential animation frame, so that animations do work.
I've also added the `spinner` view in Xilem to test this out. The `state_machine` examples uses this.
This is work done for the variable fonts demo.
=> Restore animation support - add `spinner` view

xilem/examples/mason.rs, xilem_core/src/views/fork.rs
It's jarring for the example to automatically add to the button count, so this makes it so it only increments while active is true.
=> Mason Only Add While Active

masonry/src/lib.rs, masonry/src/testing/mod.rs, xilem_core/src/deferred.rs, xilem_web/src/concurrent/memoized_await.rs
I don't think anything speaks against making the items public in masonry?
=> Fix doc links by either correcting the item name, or making these public

.github/workflows/ci.yml, xilem/Cargo.toml, xilem/examples/stopwatch.rs
This pull request adds a stopwatch example with start, stop, lap, and reset buttons.
When the stopwatch is active, the stop and lap buttons are visible. When the stopwatch is not active, the reset and start buttons are example.
To reduce resource usage, I set the timer period to 50ms, and only show 1 decimal place.
This is an older screenshot of what it looks like when it exceeds a day:
Also tested on Windows:
Let me know if there are any improvements you see that I can make.
I included the android boilerplate, but I haven't tested it.
=> Xilem stopwatch example

xilem_web/src/elements.rs
This should fix the issue described in #440 by adding the type of the `Children` `ViewSequence` to the type of element, which results in unique types, so `AnyView` should not cause issues anymore. Fortunately there's no regression with the compilation times here, so an `AnyViewSequence` doesn't seem to be necessary in that case.
=> xilem_web: Fix issue with downcasting to a wrong type transitively from `AnyView`

xilem/examples/calc.rs
On mobile platforms, setting the logical width of the window to 400 can cause the view to overflow on phones with smaller screen widths (such as the iPhone SE 2nd generation).
<details>
<summary>screenshot of the view overflow</summary>
</details>
It is more intuitive not to manually set the window size. Additionally, winit does not support set_title and set_resizable on iOS and Android (calling them does not have any effect).
=> Fix view overflow in the calc example on mobile

masonry/examples/calc_masonry.rs, masonry/src/contexts.rs, masonry/src/lib.rs, masonry/src/passes/mod.rs, masonry/src/passes/mutate.rs, masonry/src/render_root.rs, masonry/src/testing/harness.rs, masonry/src/widget/tests/mod.rs, masonry/src/widget/tests/snapshots/masonry__widget__tests__widget_tree__access_grandchild_widget.snap, masonry/src/widget/tests/widget_tree.rs, masonry/src/widget/widget.rs, masonry/src/widget/widget_mut.rs, masonry/src/widget/widget_pod.rs, masonry/src/widget/widget_state.rs
This is part of the "Pass Specification" RFC:
https://github.com/linebender/rfcs/pull/7
Rename WidgetCtx to MutateCtx.
Add a mutate pass.
Add a `mutate_later` context method to trigger that pass.
Refactor `edit_root_widget` to use a version of that pass.
Add a separate constructor for the synthetic WidgetState created in RenderRoot.
=> Implement mutate pass from pass spec RFC

masonry/src/event_loop_runner.rs, masonry/src/testing/harness.rs, masonry/src/tracing_backend.rs
Stop debug log lines from showing up between test indicators when running `cargo test`.
=> Reduce logs in tests

xilem_web/src/after_update.rs, xilem_web/src/attribute.rs, xilem_web/src/class.rs, xilem_web/src/context.rs, xilem_web/src/lib.rs, xilem_web/src/one_of.rs, xilem_web/src/style.rs, xilem_web/src/svg/common_attrs.rs, xilem_web/src/svg/kurbo_shape.rs, xilem_web/src/templated.rs
I think I've covered every pub item at the top level.
It also renames  (taking `Attributes` as example)  `start_attribute_modifier` -> `rebuild_attribute_modifier`,
and `end_attribute_modifier` -> `mark_end_of_attribute_modifier`, as I think that makes it more clear what these methods do.
`start_attribute_modifier` was a noop in `View::build` and may lead to buggy behavior when `DomNode::apply_props` is called before every parent `View::build` has done modifying the props. This should make `DomNode::apply_props` robust. And `AfterBuild` is fixed now with that.
=> xilem_web: Document a lot and remove `start_<modifier>` as it doesn't do anything in `View::build` and may be misleading

masonry/src/event.rs, masonry/src/testing/harness.rs
This brings code over from glazier for a set of PointerButtons that just uses a single value and bit flags rather than a `HashSet`.
=> masonry: More efficient set of PointerButtons.

Cargo.lock, masonry/Cargo.toml, masonry/examples/custom_widget.rs, masonry/src/box_constraints.rs, masonry/src/lib.rs, masonry/src/render_root.rs, masonry/src/text/edit.rs, masonry/src/text/layout.rs, masonry/src/text/selection.rs, masonry/src/text_helpers.rs, masonry/src/widget/checkbox.rs, masonry/src/widget/flex.rs, masonry/src/widget/image.rs, masonry/src/widget/label.rs, masonry/src/widget/portal.rs, masonry/src/widget/prose.rs, masonry/src/widget/root_widget.rs, masonry/src/widget/scroll_bar.rs, masonry/src/widget/sized_box.rs, masonry/src/widget/spinner.rs, masonry/src/widget/tests/layout.rs, masonry/src/widget/textbox.rs, masonry/src/widget/widget_pod.rs, masonry/src/widget/widget_ref.rs, masonry/src/widget/widget_state.rs
Rather than have to keep a dependency on `kurbo` at the correct version, always use it via `vello`.
This makes this match how `peniko` is already used within `masonry`.
=> masonry: Use Kurbo via Vello.

masonry/src/contexts.rs, masonry/src/debug_logger.rs, masonry/src/event.rs, masonry/src/lib.rs, masonry/src/passes/compose.rs, masonry/src/passes/mod.rs, masonry/src/render_root.rs, masonry/src/testing/helper_widgets.rs, masonry/src/tree_arena.rs, masonry/src/widget/tests/snapshots/masonry__widget__tests__lifecycle_basic__app_creation.snap, masonry/src/widget/widget.rs, masonry/src/widget/widget_pod.rs, masonry/src/widget/widget_ref.rs, masonry/src/widget/widget_state.rs
Add `Widget::compose` method.
Add `ComposeCtx` type.
Add `needs_compose`, `request_compose`, `translation_changed` flags to WidgetState.
Add `window_origin` attribute to WidgetState.
Add convenience methods to TreeArena.
Remove `needs_window_origin` flag and `parent_window_origin` attribute.
=> Implement compose pass

masonry/src/event.rs, masonry/src/event_loop_runner.rs
I opened https://github.com/linebender/xilem/issues/473 earlier today, but I realized after looking at the code that it would be super simple to implement!
Copying over some context from that issue:
- I'm working on a graph renderer using Vello.
- I'm porting it over to a Masonry widget, so that I can build a UI around it.
- In doing so I noticed there wasn't support for winit's `PinchGesture`, which I had been using before when messing around with this on my macOS device.
Please let me know if y'all feel like this is appropriate to include inside of `PointerEvent`!
=> masonry: add Pinch to PointerEvent

xilem/examples/mason.rs, xilem/examples/stopwatch.rs, xilem/examples/variable_clock.rs, xilem/src/view/mod.rs, xilem/src/view/task.rs, xilem_web/src/concurrent/mod.rs, xilem_web/src/concurrent/task.rs, xilem_web/web_examples/spawn_tasks/src/main.rs
Following [the discussion in Zulip](https://xi.zulipchat.com/#narrow/stream/354396-xilem/topic/.60async_repeat.60.20name.20brainstorming), this PR renames `async_repeat` view into `task`, and its `future_future` argument into `init_future`. I also assumed we would want to do a corresponding rename in `xilem_web` for consistency.
=> Rename async_repeat into task

masonry/src/contexts.rs, masonry/src/widget/flex.rs, masonry/src/widget/portal.rs, masonry/src/widget/widget_pod.rs
One of the problems we ran into with the `to_do_list` example was that we had a `Flex` inside a `Portal`: the `Portal` widget is designed to display scrollbars and provide scrolling if the child is larger than its constraints... but then Flex's `layout` method always clipped the returned size so it wasn't ever larger than its constraints. Hence, no scrolling. Removing the `bc.constrain(my_size)` part makes the example have scrolling behavior again.
This PR also tweaks scrolling code and adds `#[track_caller]` attributes to help with debugging.
=> Fix Portal widget

Cargo.lock, masonry/Cargo.toml, masonry/src/event_loop_runner.rs, masonry/src/tracing_backend.rs, masonry/src/widget/variable_label.rs, xilem/Cargo.toml
- Adds tracing_android_trace
- Correct the span for VariableLabel
- Make the created apps "debuggable"
- Enable spans for `wgpu`'s `profiling` results
- Add a span around the Vello rendering to show when that is
=> Improve tracing for use of Android GPU Inspector

masonry/src/text/layout.rs, masonry/src/text/mod.rs, masonry/src/text/selection.rs, masonry/src/text_helpers.rs, masonry/src/widget/variable_label.rs
If using hinting during an animation, a shimmering effect can occur.
=> Disable hinting whilst a `VariableLabel` animation is ongoing

masonry/src/text/backspace.rs
Also, wrap a URL in angle brackets to satisfy `clippy::doc_markdown`
=> masonry: Fix a dangling sentence in test comment.

Cargo.toml, masonry/src/lib.rs
=> masonry: Re-enable `clippy::doc_markdown`

masonry/src/tracing_backend.rs
The calculation of the levels was previously duplicated for both web and native, and the `WARN` level was not used properly on WASM for tests.
=> Reduce duplicated logic in  `tracing_backend`, and add some docs

masonry/src/lib.rs, masonry/src/widget/mod.rs, masonry/src/widget/screenshots/masonry__widget__sized_box__tests__empty_box_with_gradient_background.png, masonry/src/widget/screenshots/masonry__widget__sized_box__tests__label_box_with_size.png, masonry/src/widget/screenshots/masonry__widget__sized_box__tests__label_box_with_solid_background.png, masonry/src/widget/sized_box.rs, masonry/src/widget/snapshots/masonry__widget__sized_box__tests__empty_box_with_gradient_background.snap, masonry/src/widget/snapshots/masonry__widget__sized_box__tests__label_box_with_solid_background.snap, xilem/src/view/sized_box.rs
The `SizedBox` widget in Masonry had the option to set a background brush that was not exposed in its corresponding view in Xilem. The `SizedBox` view now exposes the option.
Incidentally, `BackgroundBrush::PainterFn` variant had the wrong type, as such it was not usable. A `scene` parameter is added and the closure now requires to be `Send + Sync`.
=> Enable BackgroundBrush in SizedBox view

masonry/examples/calc_masonry.rs, masonry/src/testing/helper_widgets.rs, masonry/src/widget/align.rs, masonry/src/widget/button.rs, masonry/src/widget/checkbox.rs, masonry/src/widget/flex.rs, masonry/src/widget/portal.rs, masonry/src/widget/root_widget.rs, masonry/src/widget/sized_box.rs, masonry/src/widget/split.rs, masonry/src/widget/tests/safety_rails.rs, masonry/src/widget/widget_pod.rs, xilem/src/any_view.rs, xilem/src/one_of.rs
Recursing is done inside the paint and accessibility passes since ff7635e4c281ff381433728bd070323347638f29. I believe this is the correct continuation of #522, with the removal of these methods "left for later" as mentioned in https://github.com/linebender/xilem/pull/522#issuecomment-2298610203.
One note is that Flex now debug-paints its baseline under its children, rather than over them.
=> Remove manual recursion to child `paint` and `accessibility`

masonry/src/widget/flex.rs
Fixes https://github.com/linebender/xilem/issues/559
See comment on the fix for an explanation. Essentially, the `major` value was used for multiple purposes, and this corrects into the expected "direction".
=> Fix the handling of `Flex::gap`

xilem/examples/calc.rs
This lets it get read out correctly by VoiceOver in accessibility code rather than read as a hyphen or dash.
=> xilem calc: Use Unicode minus sign.

masonry/src/widget/portal.rs, masonry/src/widget/scroll_bar.rs, masonry/src/widget/widget_ref.rs
Fixes scrolling `Portal` on scrollbar drag by recomposing instead of relayouting.
Regression probably caused in 59ee615651266421ffe65dadee6d16663f056c9d (https://github.com/linebender/xilem/pull/488) or ff7635e4c281ff381433728bd070323347638f29 (https://github.com/linebender/xilem/pull/522).
=> masonry: fix updating Portal on scrollbar drag

masonry/src/tree_arena.rs
beats reading the implementation to know the order :-)
=> masonry: add docs for `TreeArena::get_id_path`

masonry/src/widget/textbox.rs
This is just enough to allow the current content of the textbox to be read with a screen reader, until we implement full accessibility later.
=> Interim accessibility for Textbox

ARCHITECTURE.md
=> docs(#581): fix missing char in `ARCHITECTURE.md`

masonry/src/contexts.rs, masonry/src/passes/event.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs, masonry/src/widget/portal.rs, masonry/src/widget/textbox.rs
This is part of the Pass Specification RFC: https://github.com/linebender/rfcs/pull/7
Note: This PRs comes with a lot of new TODO items. Addressing most of these items is difficult without major refactors, because Portal code deals with accessing values across multiple widgets, which is still hard to do elegantly.
=> Implement update_scrolls pass

masonry/examples/calc_masonry.rs, masonry/src/contexts.rs, masonry/src/passes/event.rs, masonry/src/widget/button.rs, masonry/src/widget/checkbox.rs, masonry/src/widget/prose.rs, masonry/src/widget/scroll_bar.rs, masonry/src/widget/split.rs, masonry/src/widget/tests/status_change.rs, masonry/src/widget/textbox.rs
Also improve documentation of pointer capture.
Continuation of 59ee615651266421ffe65dadee6d16663f056c9d (https://github.com/linebender/xilem/pull/488).
Makes `has_pointer_capture` available on all context types except `LayoutCtx`, like `is_active` used to be.
=> masonry: replace `set_active` and `is_active` with pointer capture

masonry/src/event.rs, masonry/src/passes/event.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs, masonry/src/widget/textbox.rs, masonry/src/widget/widget_pod.rs
Make Textbox Widget tab-focusable.
This is part of the Pass Specification RFC: https://github.com/linebender/rfcs/pull/7
=> Implement update_focus pass

xilem/examples/widgets.rs, xilem/src/view/mod.rs
This PR adds another widget to the widgets example, and also draws boxes around each widget to separate them visually. I wanted to use flex wrap to display them, but I don't think that's implemented yet in Xilem, and the layout I did use isn't bad.
It also provides a simple example of the use of `Adapt`
=> add checkbox to widget example

masonry/src/passes/layout.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs, masonry/src/testing/helper_widgets.rs, masonry/src/widget/tests/safety_rails.rs, masonry/src/widget/tests/snapshots/masonry__widget__tests__lifecycle_basic__app_creation.snap, masonry/src/widget/widget_pod.rs, masonry/src/widget/widget_state.rs
Add update_focus_chain pass.
Add update_new_widgets pass.
Remove RenderRoot::root_lifecycle.
Move call_widget_method_with_checks out of Widgetpod.
These new passes aren't intended to stay long-term, but are meant to make future refactors easier and more concise.
The other goal is to remove almost all the remaining code in the lifecycle method.
=> Add temporary passes and remove most of lifecycle method

masonry/examples/two_textboxes.rs, masonry/src/passes/accessibility.rs, masonry/src/passes/event.rs, masonry/src/render_root.rs, masonry/src/text/selection.rs, masonry/src/widget/label.rs, masonry/src/widget/prose.rs, masonry/src/widget/textbox.rs, masonry/src/widget/variable_label.rs
=> Make `Textbox` focusable and trigger redraw in response to `request_layout`

xilem_web/Cargo.toml, xilem_web/src/attribute.rs, xilem_web/src/class.rs, xilem_web/src/element_props.rs, xilem_web/src/elements.rs, xilem_web/src/events.rs, xilem_web/src/lib.rs, xilem_web/src/pointer.rs, xilem_web/src/style.rs, xilem_web/src/text.rs
Some micro-optimizations, e.g. avoids a js call `instanceof` (via `dyn_into`/`dyn_ref`) when constructing elements.
Leads to a small speed increase when constructing/visiting elements (roughly 2%) and more importantly a leaner wasm binary (around 5 %), respectively tested with the js-framework-benchmark suite.
=> xilem_web: Optimize element casting, and intern often used strings (e.g. "div")

xilem/src/any_view.rs, xilem/src/lib.rs, xilem/src/one_of.rs, xilem/src/view/button.rs, xilem/src/view/checkbox.rs, xilem/src/view/flex.rs, xilem/src/view/grid.rs, xilem/src/view/image.rs, xilem/src/view/label.rs, xilem/src/view/portal.rs, xilem/src/view/progress_bar.rs, xilem/src/view/prose.rs, xilem/src/view/sized_box.rs, xilem/src/view/spinner.rs, xilem/src/view/textbox.rs, xilem/src/view/variable_label.rs, xilem_core/examples/filesystem.rs, xilem_core/examples/user_interface.rs, xilem_core/src/any_view.rs, xilem_core/src/element.rs, xilem_core/src/sequence.rs, xilem_core/src/views/one_of.rs, xilem_core/tests/common/mod.rs, xilem_core/tests/one_of.rs, xilem_web/src/lib.rs, xilem_web/src/one_of.rs
This is another intermediary PR for the "restrict widget creation to Mutate pass" feature.
The basic idea is that, in the near future, it will be impossible to create a WidgetPod without a handle to the arena. In my current WIP code, that handle is passed through ViewCtx. Therefore, this PR changes all the sites in xilem that create a Pod and has them use a ViewCtx method instead.
I've tested most xilem examples and they all worked (except for variable_clock, which currently panics in the last main commit).
=> Reserve ability to create Pod to ViewCtx

masonry/src/contexts.rs, masonry/src/passes/accessibility.rs, masonry/src/passes/event.rs, masonry/src/passes/update.rs, masonry/src/widget/textbox.rs, masonry/src/widget/widget_state.rs
I believe this is necessary to activate and deactivate input focus with TalkBack on Android. Assistive technologies on other platforms can also request the focus action, though none of the AccessKit backends support the blur action yet.
=> Support the AccessKit focus and blur actions 

masonry/src/render_root.rs
Requesting and resigning focus can happen when handling pointer and accessibility events, not just keyboard events.
=> Run the focus pass in post-processing for all events

masonry/src/contexts.rs, masonry/src/passes/compose.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs, masonry/src/text_helpers.rs, masonry/src/widget/textbox.rs, masonry/src/widget/widget_state.rs
Should fix the way repaints were requested every paint on some platforms.
This PR unfortunately comes with a lack of tests. TestHarness currently doesn't have good support for testing signals, but even if it did, this is an inherently visual feature that we don't really have a way to test visually.
I don't know how to trigger IME on my machine. (I'm using PopOS, a Debian variant.) If someone wants to either test this or help me get to speed, I'd appreciate it.
=> Clean up IME handling code

masonry/examples/calc_masonry.rs, masonry/examples/custom_widget.rs, masonry/src/contexts.rs, masonry/src/passes/accessibility.rs, masonry/src/testing/helper_widgets.rs, masonry/src/widget/align.rs, masonry/src/widget/button.rs, masonry/src/widget/checkbox.rs, masonry/src/widget/flex.rs, masonry/src/widget/grid.rs, masonry/src/widget/image.rs, masonry/src/widget/label.rs, masonry/src/widget/portal.rs, masonry/src/widget/progress_bar.rs, masonry/src/widget/prose.rs, masonry/src/widget/root_widget.rs, masonry/src/widget/scroll_bar.rs, masonry/src/widget/sized_box.rs, masonry/src/widget/spinner.rs, masonry/src/widget/split.rs, masonry/src/widget/textbox.rs, masonry/src/widget/variable_label.rs, masonry/src/widget/widget.rs, xilem/src/any_view.rs, xilem/src/one_of.rs
It makes more sense to pass the `NodeBuilder` reference separately to the `accessibility` method. In particular, this avoids the need to keep calling a method on `AccessCtx` to get that mutable reference.
=> Remove `current_node` from `AccessCtx`

masonry/src/contexts.rs, masonry/src/passes/layout.rs, masonry/src/widget/widget_state.rs
When the scrollbars are not being set, the calculations get NaNs. This breaks rendering, causing extreme slowdowns and artifacts.
This is discussed in [#masonry>`to_do_list`: Horrendous performance](https://xi.zulipchat.com/#narrow/stream/317477-masonry/topic/to_do_list.3A.20Horrendous.20performance)
I've made this work now using `is_explicitly_stashed` in layout. It does not currently cause issues there.
The underlying issue of `NaN`s being created (and not detected) have not been resolved.
=> Propagate the `stashed` state correctly

masonry/src/widget/widget_state.rs
`WidgetState::merge_up` no longer actually mutates `child_state` since https://github.com/linebender/xilem/issues/488 and https://github.com/linebender/xilem/pull/599, but it may do so again in the future.
See also this Zulip thread:
https://xi.zulipchat.com/#narrow/stream/317477-masonry/topic/WidgetState.3A.3Amerge_up.20no.20longer.20needs.20mutable.20child.20state
=> Add note about mutable child state in WidgetState::merge_up

xilem_web/src/attribute.rs, xilem_web/src/class.rs, xilem_web/src/element_props.rs, xilem_web/src/elements.rs, xilem_web/src/interfaces.rs, xilem_web/src/lib.rs, xilem_web/src/one_of.rs, xilem_web/src/style.rs, xilem_web/src/svg/kurbo_shape.rs, xilem_web/src/templated.rs, xilem_web/src/text.rs
This was the initial plan of #403, I can't remember anymore why I didn't made it to work back then. Anyway this should simplify the type signature of `Pod` and `PodMut` a little bit.
This also includes a little bit of refactoring otherwise (mostly aesthetic + removal of unnecessary wrapper  `DynNode`)
=> xilem_web: Refactor unnecessary generic type parameter `Props` to associated type

xilem_web/src/attribute.rs, xilem_web/src/class.rs, xilem_web/src/context.rs, xilem_web/src/element_props.rs, xilem_web/src/elements.rs, xilem_web/src/one_of.rs, xilem_web/src/style.rs, xilem_web/src/svg/common_attrs.rs, xilem_web/src/svg/kurbo_shape.rs
With the risk of wasting time with micro-optimizations...
Honestly the diff bigger and more complex than I would like it to be for the effect that this change does, so I'm sorry to reviewers.
FWIW, I tested all the examples with the feature "hydration" disabled and enabled.
In effect this reduces the amount of allocs and the size of allocs of all the modifiers (since Vec allocs at least 4 elements) by:
* Adding a size hint in modifier views, to give the actual element props a hint how much memory is needed in the relevant modifier, so that only one allocation occurs when the actual modifier is added/created.
* Using bitflags encoded in the `start_idx` to avoid extra 4 bytes for just two booleans in each modifier, and also use `u16` instead of `usize` to save another 4 bytes.
* Avoiding …
=> xilem_web: Optimize modifiers (allocs mostly), and fix hydrating SVG elements

ARCHITECTURE.md, Cargo.toml
Just noticed that it's still referenced in the `Cargo.toml`, I wonder that this is possible at all (as it points to nirvana...)
=> Remove `xilem_web_core` artifacts

.typos.toml, masonry/doc/ROADMAP.md, masonry/examples/custom_widget.rs, masonry/examples/simple_image.rs, masonry/src/widget/image.rs, masonry/src/widget/mod.rs, masonry/src/widget/screenshots/masonry__widget__image__tests__layout_contain.png, masonry/src/widget/screenshots/masonry__widget__image__tests__layout_cover.png, masonry/src/widget/screenshots/masonry__widget__image__tests__layout_fill.png, masonry/src/widget/screenshots/masonry__widget__image__tests__layout_fitheight.png, masonry/src/widget/screenshots/masonry__widget__image__tests__layout_fitwidth.png, masonry/src/widget/screenshots/masonry__widget__image__tests__layout_none.png, masonry/src/widget/screenshots/masonry__widget__image__tests__layout_scaledown.png, xilem/src/view/image.rs
Reimplement calculation of image size in `Image` widget `layout` function.
Makes it match against `self.fill` before setting size.
Tests still missing.
Fixes #574
=> feat(#574): reimplementation of `Image` widget `layout` function

Cargo.lock, masonry/Cargo.toml, masonry/README.md, masonry/src/event_loop_runner.rs, masonry/src/lib.rs, masonry/src/tracing_backend.rs
This is very useful for debugging performance issues. I've already used it to debug [#masonry>`to_do_list`: Horrendous performance](https://xi.zulipchat.com/#narrow/stream/317477-masonry/topic/to_do_list.3A.20Horrendous.20performance).
Setting a feature works on a workspace-wide basis. I.e `cargo run --example mason --features tracy` works.
Some weirdness:
- Tracy seems to assume we know when a frame will "start", but we only know if we'll repaint once processing for an event has finished.
- Something seems to be starting a default "Frame", which isn't really right. We don't have any continuous frames. Maybe we should always request a redraw if tracy is enabled.
Either way, I think this feature is useful  to land *now*, so am not planning on resolving these in this PR unless someone …
=> Connect to tracy if the `tracy` feature is enabled

masonry/src/contexts.rs, masonry/src/widget/widget.rs, masonry/src/widget/widget_state.rs
This adds public getters for clip path to non-`LayoutCtx` contexts, and also to `WidgetState` as it seems relevant for painting.
The motivation is to remove private field accesses from `Widget::get_child_at_pos` as mentioned in
https://github.com/linebender/xilem/pull/565#issuecomment-2374162416.
This leaves one private field access, namely `WidgetState::is_stashed`. As per the docs of `WidgetState` ("widgets will generally not interact with it directly"), that field perhaps should not be publicly accessible from `WidgetState`, but then it should be accessible from `WidgetRef`.
=> Add public methods to access clip path

masonry/src/text/edit.rs, masonry/src/text/selection.rs, masonry/src/widget/prose.rs
There was no good reason for selection to be optional, except to not display it when focus was lost. This is now handled with a boolean flag. A side-effect of this is that TextWithSelection now remembers its selection when focus is gained back.
Selection was used with a default value of `(0, 0)` in cases where it was `None`, so its default value in similar cases is still `(0, 0)`.
=> Make selection non-optional in TextWithSelection

masonry/src/widget/scroll_bar.rs
This isn't used and is just marked as dead code. It feels like a historical artifact.
=> masonry: `Scrollbar`: Remove unused `hovered` field

masonry/src/contexts.rs, masonry/src/passes/layout.rs
That field has been made redudant by the update_pointer pass, and is no longer used.
=> Remove LayoutCtx::mouse_pos

masonry/src/passes/accessibility.rs
The main reason to do this is I'd like to stick to a pattern where all the recursive pass functions call widget methods directly. I believe this makes the code much easier to read and understand, even if you don't consciously notice this pattern.
=> Tweak build_access_node function

masonry/src/contexts.rs, masonry/src/passes/update.rs, masonry/src/widget/tests/safety_rails.rs, masonry/src/widget/widget.rs
This gives a beginner-friendly error in cases where Masonry detects that `register_children()` was improperly implemented.
=> Add safety rail for register_children method

masonry/src/passes/layout.rs, masonry/src/widget/align.rs, masonry/src/widget/button.rs, masonry/src/widget/checkbox.rs, masonry/src/widget/flex.rs, masonry/src/widget/image.rs, masonry/src/widget/label.rs, masonry/src/widget/progress_bar.rs, masonry/src/widget/prose.rs, masonry/src/widget/sized_box.rs, masonry/src/widget/spinner.rs, masonry/src/widget/split.rs, masonry/src/widget/textbox.rs, masonry/src/widget/variable_label.rs
Each widget implementation was doing its own bespoke tracing in layout. This removes the bespoke tracing and adds a trace inside the layout pass logging the same information in a more centralized way.
=> Remove tracing boilerplate from widget code

masonry/src/contexts.rs, masonry/src/debug_logger.rs, masonry/src/lib.rs, masonry/src/testing/harness.rs, masonry/src/widget/mod.rs, masonry/src/widget/portal.rs, masonry/src/widget/tests/layout.rs, masonry/src/widget/tests/status_change.rs, masonry/src/widget/widget.rs, masonry/src/widget/widget_mut.rs, masonry/src/widget/widget_ref.rs, masonry/src/widget/widget_state.rs
This enforces a pattern in the codebase where that WidgetState can only be accessed through pass contexts, which prevents invalidation bugs.
=> Make WidgetState private

masonry/src/render_root.rs
Add a method which brute-force resets the paint and accessibility flags for all widgets.
This is useful for rescale, and for testing purposes where you want a quick and dirty way to repaint everything.
=> Add RenderRoot::request_render_all method

xilem_web/src/interfaces.rs, xilem_web/src/one_of.rs, xilem_web/src/style.rs, xilem_web/web_examples/svgtoy/src/main.rs
This sketches/implements (parts of) the transform modifier API described in [Add `Affine` transform to `Widget` trait?](https://xi.zulipchat.com/#narrow/stream/317477-masonry/topic/Add.20.60Affine.60.20transform.20to.20.60Widget.60.20trait.3F/near/472076600) for xilem_web.
This currently includes `rotate` and `scale`, because there are less cases to handle for these [CSS transform functions](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function).
In `rotate` I think we can reduce this to just radians (there are more units for `<angle>`: `turn`, `grad`, `deg` and `rad` (used here) but they can all be derived from radians), and percent in scale is kinda redundant (as `200%` == `2.0`)), for example `translate` has more cases as it includes all kinds of units (like `px`, `em`, …
=> xilem_web: Add `Rotate` and `Scale` (CSS) transform views

xilem_web/src/interfaces.rs
I missed comment artifacts in #621, added doc-comment/test for `SvgElement` and put the `WithStyle` on the `Element` interface bounds, as it plays better with rust-analyzer and is more consistent with the other API.
=> xilem_web: Remove some comment artifacts, put `WithStyle` bound to `Element` interface and document `Element::style`

masonry/src/app_driver.rs, masonry/src/render_root.rs, masonry/src/widget/widget_state.rs, xilem/src/driver.rs, xilem/src/lib.rs, xilem/src/view/button.rs, xilem/src/view/checkbox.rs, xilem/src/view/flex.rs, xilem/src/view/grid.rs, xilem/src/view/label.rs, xilem/src/view/progress_bar.rs, xilem/src/view/prose.rs, xilem/src/view/textbox.rs, xilem/src/view/variable_label.rs
These methods will be used with #639 to implement a fixpoint loop for rewrite passes.
This also lets us remove `mark_changed`, since we can use `content_changed` for the same purpose.
=> Add needs_rewrite_passes and content_changed methods

masonry/src/event_loop_runner.rs, masonry/src/passes/compose.rs, masonry/src/passes/event.rs, masonry/src/passes/layout.rs, masonry/src/passes/mutate.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs, masonry/src/testing/harness.rs, masonry/src/widget/tests/snapshots/masonry__widget__tests__lifecycle_basic__app_creation.snap
Create run_rewrite_passes function.
Remove redundant uses of synthetic WidgetState.
Small bugfixes.
Move RenderRoot::root_layout code into the layout pass. Rename update_new_widgets pass to update_widget_tree.
=> Refactor rewrite passes

masonry/src/contexts.rs, masonry/src/event.rs, masonry/src/passes/accessibility.rs, masonry/src/passes/layout.rs, masonry/src/passes/update.rs, masonry/src/testing/helper_widgets.rs, masonry/src/widget/button.rs, masonry/src/widget/checkbox.rs, masonry/src/widget/label.rs, masonry/src/widget/portal.rs, masonry/src/widget/prose.rs, masonry/src/widget/tests/safety_rails.rs, masonry/src/widget/tests/snapshots/masonry__widget__tests__lifecycle_basic__app_creation.snap, masonry/src/widget/textbox.rs, masonry/src/widget/widget.rs, masonry/src/widget/widget_state.rs
Replace with `Widget::accepts_xxx()` methods
Tweak accessibility code
Remove `BuildFocusChain` event
Remove `WidgetState::is_portal`, `register_as_portal()`, and overall remove the idea of a first-class "portal" concept.
=> Remove register methods

masonry/src/text/selection.rs, masonry/src/text/text_layout.rs, masonry/src/widget/label.rs, masonry/src/widget/progress_bar.rs, masonry/src/widget/prose.rs, masonry/src/widget/textbox.rs, masonry/src/widget/variable_label.rs
Remove type parameter from TextLayout.
Tweak error message in text widgets.
This makes the TextLayout code slightly simpler (though with more invariants) in anticipation of splitting it into its own crate.
=> Stop storing text in TextLayout

masonry/examples/calc_masonry.rs, masonry/src/box_constraints.rs, masonry/src/contexts.rs, masonry/src/passes/layout.rs, masonry/src/passes/update.rs, masonry/src/tree_arena.rs, masonry/src/widget/flex.rs, masonry/src/widget/grid.rs, masonry/src/widget/tests/safety_rails.rs, masonry/src/widget/widget_state.rs
Merge call_widget_method_with_checks, run_layout_inner and run_layout_on.
Remove needs_visit flag.
Add checks for invalid values in place_child, set_child_translation and run_layout.
=> Refactor safety rails for layout pass

masonry/src/text/selection.rs, masonry/src/text/text_layout.rs, masonry/src/widget/prose.rs, masonry/src/widget/textbox.rs
This adds the necessary AccessKit properties and child nodes to expose detailed information about text widgets. It also supports the `SetTextSelection` action.
=> Accessibility for text

masonry/src/passes/accessibility.rs, masonry/src/passes/compose.rs, masonry/src/passes/event.rs, masonry/src/passes/layout.rs, masonry/src/passes/paint.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs
This means all the pass functions now have the same naming convention, which makes the code more grep-able.
=> Rename pass functions from root_xxx to run_xxx_pass

masonry/src/render_root.rs, masonry/src/widget/widget_ref.rs
I'm pretty sure this method never caught a single bug.
I think the idea of a "safety net" that checks invariants are upheld by passes (without trusting pass code) has merit, but it should be based on a survey of previous bugs in pass code.
=> Remove debug_validate method

masonry/src/passes/anim.rs, masonry/src/passes/event.rs, masonry/src/passes/mod.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs, masonry/src/testing/harness.rs
Reorder update passes so their code is in the same order as they're run.
Split out anim pass to a separate file (since it's not run with the other passes).
This is strictly cut-and-paste, no code has been changed.
=> Reorder update passes

masonry/src/event.rs, masonry/src/passes/anim.rs, masonry/src/testing/helper_widgets.rs, masonry/src/widget/spinner.rs, masonry/src/widget/tests/snapshots/masonry__widget__tests__lifecycle_basic__app_creation.snap, masonry/src/widget/variable_label.rs, masonry/src/widget/widget.rs
This marks animation as something that's somewhere between an event (it's triggered externally, it can't be requested synchronously as part of rewrite passes) and an update (it takes the same context type, and isn't tied to a user interaction).
=> Create on_anim method

masonry/src/widget/button.rs, masonry/src/widget/checkbox.rs, masonry/src/widget/label.rs, masonry/src/widget/tests/status_change.rs
The whole reason the Label widget exists is as a non-interactive text holder for higher-level widgets. Therefore, it isn't meaningful for it to have interactivity.
More concretely, there is no interactivity currently implemented
=> Remove potential interactivity from `Label`

masonry/src/text/text_layout.rs
cc for awareness @mwcampbell.
That field was dead code left behind when we removed previous links support. On that struct is probably not the right field for links to live, since `Label` also uses `TextLayout`, but can't meaningfully support links as part of a different interactive widget.
=> Remove the dead `links` field from TextLayout

masonry/src/contexts.rs, masonry/src/passes/accessibility.rs, masonry/src/passes/anim.rs, masonry/src/passes/compose.rs, masonry/src/passes/layout.rs, masonry/src/passes/mod.rs, masonry/src/passes/paint.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs
This can be toggled using the `MASONRY_TRACE_PASSES` environment variable.
This is as-discussed in [#xilem > Scrolling is insanely laggy](https://xi.zulipchat.com/#narrow/channel/354396-xilem/topic/Scrolling.20is.20insanely.20laggy). There are a few overlapping issues, but this *significantly* improves performance in debug mode.
The main pass which was problematic was the compose pass, however this also had a significant impact on the time taken by the accessibility/paint passes.
This only applies to the passes which traverse the entire tree, so not the targeted passes. I also chose to exclude update_disabled and update_stashed, as those will not necessarily happen to all widgets.
This also significantly reduces the size of the created log files - see [#masonry > Heavy amounts of logs …
=> Don't use full tracing spans in full-tree passes by default

masonry/src/event.rs, masonry/src/event_loop_runner.rs, masonry/src/passes/event.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs, masonry/src/widget/widget.rs
Inspired by #687, I thought some more tidying up of the log file was in order.
The main differences are:
1) Higher-scale spans exist for key operations
2) Something is always logged for each event, but less for high-density eventskey 
3) Less is logged for high-density events
4) Key repeats are no longer treated as high density
5) We no longer do extra work if the hover and focus paths haven't changed (which also means less logging)
This PR *does not* depend on #687
=> Refactor tracing handling for events

masonry/src/widget/widget.rs
Users could easily run into difficulties where animation does not work as expected, with no obvious hints for how to debug this. Documenting the correct usage of `on_anim_frame` should help them.
=> Give actionable suggestions for implementing `on_anim_frame`

xilem_web/src/svg/kurbo_shape.rs
Regressed in #699
cc @Philipp-M 🦆
=> Fix kurbo::BezPath d attribute for xilem_web::svg::path element

xilem_web/src/elements.rs, xilem_web/src/interfaces.rs, xilem_web/src/lib.rs, xilem_web/src/modifiers/attribute.rs, xilem_web/src/modifiers/class.rs, xilem_web/src/modifiers/elements.rs, xilem_web/src/modifiers/elements/mod.rs, xilem_web/src/modifiers/mod.rs, xilem_web/src/modifiers/overwrite.rs, xilem_web/src/modifiers/style.rs, xilem_web/src/one_of.rs, xilem_web/src/props/element.rs, xilem_web/src/props/html_input_element.rs, xilem_web/src/props/mod.rs, xilem_web/src/svg/common_attrs.rs, xilem_web/src/svg/kurbo_shape.rs, xilem_web/web_examples/fetch/src/main.rs, xilem_web/web_examples/todomvc/src/main.rs
This PR starts with supporting specialized elements (i.e. more than just the `Element` DOM interface), starting with boolean attributes in `HtmlInputElement`  (`checked`, `default_checked`, `disabled`, `required`, `multiple`).
With a general `OverwriteBool` modifier which is optimized by encoding boolean flags into a `u32`, thus not requiring allocations (compared to the other modifiers we currently have), but is limited to max 32 overwrites, which I don't think should be a real-world limitation (i.e. `input_el.checked().checked()...checked()` 32 times makes no sense), I also started adding tests for this, as it juggles around with bit-operations (and we should generally start writing more tests).
I have originally planned to feature-flag this (i.e. have a feature like …
=> xilem_web: Add a few boolean attribute modifiers for `HtmlInputElement` and factor element state flags out of these modifiers into `ElementFlags`

masonry/src/lib.rs
This is a pub enum within `render_root` and is required for creating a `RenderRootOptions` which is already exported. This is needed for people embedding masonry in a non-Xilem way.
=> masonry: Export `WindowSizePolicy`

masonry/examples/calc_masonry.rs
=> masonry example: Fix reference to `on_status_changed`

masonry/src/lib.rs
This is needed for `Align::horizontal`, `Align::vertical`, etc.
=> masonry: Export `UnitPoint`

.github/workflows/ci.yml
This PR swaps the order of the `--each-feature` and `--optional-deps` flags.
This is the order in the newer standard, as seen in e.g. [peniko](https://github.com/linebender/peniko/blob/7940e7de0aa09673f522a8386d91cd081af98e87/.github/workflows/ci.yml#L114): `--optional-deps --each-feature --features std`.
This helps with the goal of keeping all the CI scripts as identical as possible.
---
This PR also adds some missing comments compared to [vello](https://github.com/linebender/vello/blob/4c6f75f499a225c4a97df71ade47b0ccc3a5096b/.github/workflows/ci.yml#L42-L44) and removes a trailing slash to match the [style of vello](https://github.com/linebender/vello/blob/4c6f75f499a225c4a97df71ade47b0ccc3a5096b/.github/workflows/ci.yml#L247-L249) as well.
=> Use standard cargo parameter order in CI.

xilem_web/src/after_update.rs, xilem_web/src/elements.rs, xilem_web/src/events.rs, xilem_web/src/interfaces.rs, xilem_web/src/lib.rs, xilem_web/src/modifiers/mod.rs, xilem_web/src/modifiers/overwrite.rs, xilem_web/src/one_of.rs, xilem_web/src/pod.rs, xilem_web/src/pointer.rs, xilem_web/src/props/element.rs, xilem_web/src/props/html_input_element.rs, xilem_web/src/templated.rs, xilem_web/src/text.rs
This renames the `ElementFlags` into `PodFlags` as these are general enough to keep them directly in the `Pod(Mut)`.
This reduces duplicated code (and thus a potential of making errors) in the props (that logic is now in `PodMut::drop`, `SuperElement::upcast` and `AnyElement::replace_inner`).
The `WithModifier` trait is adjusted and only implemented on the `View::Element` with a blanket impl of `AsMut<T>` instead (which should also reduce boilerplate), this was mostly a necessity to avoid `impl WithModifier` for either variants `Pod` and `PodMut` on every props (i.e. more boilerplate).
Further all kinds of event views were fixed, as they would break currently when the underlying element changes (e.g. via a variant change of `OneOf`). This was actually the original planned change, but I …
=> xilem_web: Fix event views (when the underlying element was recreated) and factor flags and `Pod` into its own module

.github/workflows/ci.yml, masonry/Cargo.toml, masonry/src/doc/01_creating_app.md, masonry/src/doc/02_implementing_widget.md, masonry/src/doc/03_implementing_container_widget.md, masonry/src/doc/04_testing_widget.md, masonry/src/doc/05_pass_system.md, masonry/src/doc/06_masonry_concepts.md, masonry/src/lib.rs, xilem/Cargo.toml, xilem/src/lib.rs, xilem/src/one_of.rs, xilem_core/Cargo.toml, xilem_core/src/deferred.rs, xilem_core/src/lib.rs, xilem_core/src/sequence.rs, xilem_web/Cargo.toml, xilem_web/src/elements.rs, xilem_web/src/lib.rs, xilem_web/src/pod.rs
* Treat doc warnings as errors. Historically we've not done so due to various `rustdoc` bugs giving false positives but I got it to pass without failure right now, so perhaps better times have arrived.
* Target only `x86_64-unknown-linux-gnu` on docs.rs as we don't have any platform specific docs.
* Properly enable example scraping for `xilem`, `xilem_core`, and `masonry`. Fully disable it for `xilem_web` which does not have examples as Cargo defines them.
* Pass `--all-features` at docs.rs to match our CI and reduce the maintenance burden of manually syncing the features list.
* Enable the `doc_auto_cfg` feature for docs.rs which will show a little tip next to feature gated functionality informing of the crate feature flag.
* Replaced `[!TIP]` with `💡 Tip` that was inside `<div …
=> Match CI doc testing with docs.rs.

Cargo.lock, Cargo.toml, xilem_web/src/pointer.rs, xilem_web/web_examples/svgdraw/Cargo.toml, xilem_web/web_examples/svgdraw/index.html, xilem_web/web_examples/svgdraw/src/main.rs, xilem_web/web_examples/svgtoy/src/main.rs
Add a simple example showing, that svg nodes can also be used similarly as a `CanvasRenderingContext2D` to draw some lines. This takes advantage of a `kurbo::QuadSpline` to avoid sharp edges  when the pointer moves fast.
See [this](https://xi.zulipchat.com/#narrow/channel/354396-xilem/topic/web.3A.20Canvas.20options.20set.20with.20.60after_build.60.20doesn't.20persist) zulip topic for more context.
This could potentially be optimized further (don't clone/recalculate all the lines every reconciliation), but I think in its current state it's also a good test to see how a naive implementation performs, and so far it's not too bad. 
Btw. as noted [here](https://github.com/linebender/xilem/pull/715#issuecomment-2438408323) this implicitly also adds the `BezPath` as the example (for more manual …
=> xilem_web: Add `svgdraw` example

xilem_web/src/events.rs, xilem_web/src/interfaces.rs, xilem_web/src/pointer.rs, xilem_web/web_examples/counter/src/main.rs
As [this Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1675847) is finally fixed, we can be more close to the spec with the `click/auxclick/contextmenu` events by using a `PointerEvent` instead of a `MouseEvent`.
I've also noticed that the DOM interface bounds/types were out of sync with the event types (bounds), this was corrected as well.
Additionally all the `pointer...` events were added.
And a simple `PointerMsg::position() -> Point` accessor.
=> xilem_web: Add pointer events and fix bounds on event listeners and correct event type for mouse events.

masonry/src/contexts.rs, masonry/src/event_loop_runner.rs, masonry/src/render_root.rs, masonry/src/testing/harness.rs
This is the first merge-able part of #606.
It allows to implement custom CSDs via window management signals and a new `WindowHandle` widget which is useful to implement a custom titlebar.
=> Add basic window control

xilem_core/src/message.rs, xilem_core/src/view.rs, xilem_web/src/templated.rs
I needed this in xilem_web, I could've used `Arc` as well, but I think it's fine to add this for consistency when an `Arc` is not needed.
It's basically copy-pasta of the `Arc`. (I don't think a macro is worth it here?). Had to fix some resulting issues in the `Templated` view (due to ambiguity?).
=> xilem_core: implement `View` for `Rc<impl View>`

xilem/src/driver.rs, xilem_core/src/any_view.rs, xilem_core/src/deferred.rs, xilem_core/src/docs.rs, xilem_core/src/element.rs, xilem_core/src/lib.rs, xilem_core/src/message.rs, xilem_core/src/sequence.rs, xilem_core/src/view.rs, xilem_core/src/views/adapt.rs, xilem_core/src/views/fork.rs, xilem_core/src/views/map_action.rs, xilem_core/src/views/map_state.rs, xilem_core/src/views/memoize.rs, xilem_core/src/views/one_of.rs, xilem_core/src/views/run_once.rs, xilem_web/src/lib.rs
This also updates to use `core::error::Error` now that it is stable.
=> Fix `missing_debug_implementations` in Xilem Core

masonry/src/widget/mod.rs, masonry/src/widget/screenshots/masonry__widget__sized_box__tests__label_box_with_background_and_padding.png, masonry/src/widget/screenshots/masonry__widget__sized_box__tests__label_box_with_outer_padding.png, masonry/src/widget/screenshots/masonry__widget__sized_box__tests__label_box_with_padding.png, masonry/src/widget/sized_box.rs, masonry/src/widget/snapshots/masonry__widget__sized_box__tests__label_box_with_padding.snap, masonry/src/widget/snapshots/masonry__widget__sized_box__tests__label_box_with_padding_and_background.snap, masonry/src/widget/snapshots/masonry__widget__sized_box__tests__label_box_with_padding_outside.snap, xilem/examples/http_cats.rs, xilem/src/view/sized_box.rs
- Added new padding attribute to sized_box Masonry widget.
- 3 unit tests demonstrating how padding is used.
- Added `Padding` struct with convenience methods for working with paddings.
- Updated `http_cats` example to use padding when more convenient and fixed hack.
```rs
sized_box(label("hello world")).padding(10.) // Equal padding on all edges
sized_box(label("hello world")).padding(Padding::top(10.)) // Padding only on top edge
sized_box(label("hello world")).padding((10., 20., 30., 40.)) // Different padding for each edge
```
Added padding on the left in the `http_cats` example, to make it more balanced with the right side.
In swiftUI the view modifier [`.frame()`](https://developer.apple.com/documentation/swiftui/view/frame(width:height:alignment:)) is used to change the size of a …
=> Add padding attribute to `sized_box` view

xilem_core/src/any_view.rs, xilem_core/src/lib.rs, xilem_core/src/views/fork.rs, xilem_core/src/views/memoize.rs, xilem_core/src/views/one_of.rs, xilem_core/src/views/orphan.rs, xilem_core/src/views/run_once.rs
Most of the change is remove the `expect` and run `cargo fix`.
For the orphan view, I've added a blanket exception. At the moment, this only applies to String, but the
I did try using `#![no_implicit_prelude]` in that module, but there are a lot of useful things in the implicit prelude, it was worse than the exception.
=> Fix `unused_qualifications` in Xilem Core

xilem_web/src/interfaces.rs, xilem_web/web_examples/fetch/src/main.rs, xilem_web/web_examples/mathml_svg/src/main.rs, xilem_web/web_examples/svgdraw/index.html, xilem_web/web_examples/svgdraw/src/main.rs, xilem_web/web_examples/todomvc/src/main.rs
This allows zooming with the mousewheel and panning with the mid/right mouse button.
I think it would be nice to add touch support with a pinch gesture handler as well.
It also replaces the random color with a color selector. And makes the stroke width range logarithmic.
And adds `type_` and `name` attributes to `HtmlInputElement`.
It was also optimized by using an `Rc<AnyDomView>` to memoize all previously drawn lines. This way I think the bottleneck now certainly is the browser.
=> xilem_web: Extend `svgdraw` example to be an infinite zoomable canvas

xilem_core/src/views/one_of.rs
Note, this fix is only excluding the false positives as a result of: https://github.com/rust-lang/rust-clippy/issues/10780
When/if the fix for that (https://github.com/rust-lang/rust-clippy/pull/13677) trickles onto stable, we can remove the expects.
=> Fix `shadow_unrelated` in Xilem Core

masonry/src/text/backspace.rs, xilem_core/examples/filesystem.rs, xilem_core/src/deferred.rs, xilem_core/src/element.rs, xilem_core/src/lib.rs, xilem_core/src/message.rs, xilem_core/src/view.rs, xilem_core/src/views/one_of.rs, xilem_core/src/views/orphan.rs, xilem_core/tests/common/mod.rs
All fixes except for removing the `expect`s are results from `cargo fix`.
=> Fix `clippy::use_self` in Xilem Core

xilem_web/src/context.rs, xilem_web/src/vecmap.rs
Also adds `MessageThunk::enqueue_message` for convenience (basically `MessageThunk::push_message` delayed with `queueMicrotask`).
See https://github.com/slowtec/xilem-leaflet/pull/4 for a use-case of this.
=> xilem_web: Add `ViewCtx::as_owned` to allow composing the view context in custom view contexts

.github/debug_assertions.sh, .github/workflows/ci.yml, Cargo.toml, xilem_core/src/lib.rs
When a workspace uses `debug_assertions` for conditional compilation (*like Xilem does*), especially of the `#[cfg(debug_assertions)]` kind, it is not sufficient to just test with it either set to `true` or `false`. Both need testing as we don't know in advance which path contains faulty code.
An initial response to this issue was done in #431 which added some `--release --all-targets` steps to the CI.
This PR here improves that verification in some key ways:
* In addition to the stable toolchain, also verify MSRV.
* Only turn off the `debug_assertions` configuration option as that is the differentiator for our testing. The full `--release` option spends time on optimizations. It may be worth doing occasional `--release` tests to detect bugs in code optimization, but those checks aren't …
=> Add more robust `debug_assertions` verification to CI.

.clippy.toml, Cargo.toml, masonry/src/lib.rs, xilem/examples/calc.rs, xilem/examples/stopwatch.rs, xilem/src/lib.rs, xilem_core/src/lib.rs, xilem_web/src/lib.rs, xilem_web/src/modifiers/style.rs
Some examples needed minor adjustments and `xilem_web` needed an exception.
=> Update to Linebender lint set v2.

masonry/src/contexts.rs, masonry/src/passes/accessibility.rs, masonry/src/widget/root_widget.rs
This is better than having to apply the scale factor to the bounding rectangles of all nodes, especially when we take externally generated AccessKit nodes, such as those generated by Parley, into account.
=> Set a transform on the root AccessKit node

masonry/src/app_driver.rs, masonry/src/contexts.rs, masonry/src/tree_arena.rs, masonry/src/widget/widget_mut.rs, masonry/src/widget/widget_ref.rs, xilem_core/src/lib.rs, xilem_core/src/views/adapt.rs, xilem_core/tests/common/mod.rs, xilem_web/src/elements.rs, xilem_web/src/lib.rs
Result from `__CARGO_FIX_YOLO=1 cargo clippy --fix`.
As newest nightly clippy bleats about all of this.
=> Eliminate needless lifetimes

masonry/src/passes/update.rs, masonry/src/text/editor.rs, masonry/src/widget/text_area.rs
This adds IME support back into Masonry. This sticks close to https://github.com/linebender/parley/pull/111, except that during IME compose, this version doesn't allow changing the selection anchor, making the code simpler. For reference, there's also https://github.com/linebender/parley/pull/136.
This tweaks the focus update pass: when a widget with IME is unfocused, Masonry sends the platform's IME disable event to the newly focused widget. As a workaround, we synthesize an IME disable event in the focus pass and send it to the widget that is about to be unfocused. A complication is that the handling of that event can request focus to a different widget, and in particular, can request itself to be focused again. This handles that case, too.
Remaining work is setting the IME candidate …
=> Re-add IME support

masonry/src/widget/text_area.rs
The user may be composing when the `TextArea` text is programmatically changed. This change clears the compose state in order to adhere to the `PlainEditor` requirements. It is disruptive, but we already warn about disruption (and about IME in particular) in the documentation of `TextArea::reset_text`.
This doesn't reset the platform's IME state, we could do, but that's potentially even more disruptive, and looks like it's a bit harder to wire up. We could also re-insert the preedit text. That'd be nicest to do if we can query `PlainEditor` for the current preedit text, which requires an API change there.
=> Clear compose in TextArea::reset_text

masonry/src/event_loop_runner.rs
This works around a janky behaviour where IME content is transferred to new instances of the same app.
This might not be needed on other systems, but I don't think that this change can cause any harm either.
=> Stop IME just before shutting down

.github/workflows/ci.yml, masonry/README.md, masonry/src/lib.rs
Update the Masonry readme with documentation on how it is generated and change the heading level to be consistent with Color
=> heading level and doc for masonry readme

tree_arena/src/tree_arena_safe.rs
This should improve performance in cases with where a widget has a very large number of direct children.
=> Use Hashmap to track TreeArena node's children

xilem_web/web_examples/todomvc/src/main.rs
Previously the complete count of todo items were shown, but only active (i.e. non-completed) todos should be considered in the count.
In the original todomvc implementation (e.g. [react](https://todomvc.com/examples/react/dist/)), I haven't found the `<strong>` node as well, so that is just combined as a single text node.
=> xilem_web: Fix todomvc example (items left in footer)

.github/workflows/ci.yml
GitHub Actions itself capitalizes the first word, e.g. the first step is always *Set up job*. This PR matches that style in our own steps. For the steps that are referencing lowercase commands the PR prepends *Run* as that is also what GitHub uses, e.g. *Run actions/foo@v3*.
Beyond the capitalization changes the Rust toolchain version is now in the step name for quicker glance value.
=> Capitalize CI step names.

.github/workflows/ci.yml
The current `matrix.os == 'ubuntu-latest'` expression works, but will fail if we for some reason need to switch to explicitly use e.g. `ubuntu-24.04`. Doing the same check via `runner.os == 'Linux'` disconnects the check from the specific OS version.
=> Disconnect the CI OS detection from the OS version.

masonry/examples/hello_masonry.rs, masonry/src/lib.rs, masonry/src/widget/variable_label.rs, xilem/examples/mason.rs, xilem/examples/variable_clock.rs, xilem/src/lib.rs, xilem/src/view/label.rs, xilem/src/view/variable_label.rs
Right now, there are uses of `Weight` from Fontique, `TextWeight` from Masonry, and `FontWeight` from Parley.
We should just use a single name.
=> Consistently use `FontWeight` as the name

.github/workflows/ci.yml, Cargo.toml
Turning off debug info in CI gives us tiny speedups, with potential for more [in some scenarios](https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html#avoid-linking-debug-info). Most notably there is 30% space savings on artifact size in Linux, really helping with cache pressure and compression/decompression time.
We don't really need the benefits of debug info in the CI environment. We're not attaching debuggers there and in case of panics we can still get a backtrace. Thus it's just wasted effort to generate the debug info and then to link it in and cache it.
I did some minor benchmarking on three different OS setups with Rust 1.83. Every step was repeated four times (1 warmup, then 3 for measuring), but stuff like CPU boost frequency etc was …
=> Disable debug info compilation in CI to boost performance.

Cargo.lock, Cargo.toml, tree_arena/Cargo.toml, tree_arena/src/tree_arena_safe.rs, tree_arena/src/tree_arena_unsafe.rs
As noted in https://github.com/linebender/xilem/pull/772#pullrequestreview-2485087588, this seems to be a really cheap but quite effective optimization, as we have `hashbrown` already in our dependency tree.
I've noticed speedups of the rewrite passes of up to >100%.
On average about 20-50% and is also definitely noticeable (smoother and less latency).
Another quite interesting observation with my (admittedly not really reproducible) performance tests,
is that the safe tree arena is actually faster than the unsafe version (roughly 10-30%), and tells yet another time that benches are really important while optimizing...
Rough overview of my performance tests/benches:
I've mostly hovered over 10000 buttons in the mason example while testing, but every second or so a new button is spawned …
=> tree_arena: Use `hashbrown::HashMap` as drop-in replacement to optimize tree-access

masonry/src/event_loop_runner.rs
=> Render one frame before showing the window to avoid flashing

.github/workflows/ci.yml, tree_arena/Cargo.toml
The CI `RUST_MIN_VER_PKGS` configuration variable was meant to track packages that are intended for publishing in order to limit MSRV checks to only those packages. This same goal can be achieved universally without the need for a configuration variable via the `--ignore-private` `cargo-hack` option.
The immediate effect on this repo is that `xilem_core` is no longer part of the MSRV check because it has `publish = false`. That is fine, because the MSRV check will run just before publishing, triggered by the PR that will remove `publish = false`, ensuring that the MSRV is accurate before publishing.
=> Replace CI `RUST_MIN_VER_PKGS` with `--workspace --ignore-private`.

Cargo.lock, Cargo.toml, masonry/src/contexts.rs, masonry/src/passes/compose.rs, masonry/src/passes/update.rs, masonry/src/render_root.rs, masonry/src/widget/text_area.rs
This adds the required context methods for (re)setting the IME area. These are added to the mutable context types, which I believe is the right place.
`TextArea` now uses `PlainEditor::ime_cursor_area` to report its IME area.
Note Masonry currently reports new IME cursor areas only when the widget itself moves or the focus changes to a new widget, but Parley's `PlainEditor` determines the IME cursor area based on the selection and preedit state of the editor, meaning the area can change based on events as well. Other widgets may choose to have different behavior still.
(It appears Masonry currently doesn't account for the IME area potentially changing based on relayout, which may be a bug.)
This replaces the old IME area reporting with a check at the end of the rewrite pass to see if IME …
=> Improve IME area reporting and set IME area in `TextArea`

masonry/src/widget/sized_box.rs, xilem/src/view/sized_box.rs
This allows for a richer appearance by using any valid brush for the border.
=> Sized Box: Use a brush for the border

masonry/src/widget/sized_box.rs
This isn't used, is marked as dead code, and is not public outside of the crate.
=> Remove unused `SizedBox::width_and_height`

masonry/examples/calc_masonry.rs
=> Remove redundant code in calc_masonry example

masonry/src/action.rs, masonry/src/box_constraints.rs, masonry/src/contexts.rs, masonry/src/debug_logger.rs, masonry/src/doc/01_creating_app.md, masonry/src/doc/03_implementing_container_widget.md, masonry/src/doc/05_pass_system.md, masonry/src/event.rs, masonry/src/passes/accessibility.rs, masonry/src/passes/compose.rs, masonry/src/passes/event.rs, masonry/src/passes/layout.rs, masonry/src/passes/mutate.rs, masonry/src/passes/paint.rs, masonry/src/passes/update.rs, masonry/src/testing/helper_widgets.rs, masonry/src/text/mod.rs, masonry/src/widget/align.rs, masonry/src/widget/button.rs, masonry/src/widget/flex.rs, masonry/src/widget/scroll_bar.rs, masonry/src/widget/sized_box.rs, masonry/src/widget/textbox.rs, masonry/src/widget/widget.rs, masonry/src/widget/widget_pod.rs, masonry/src/widget/widget_ref.rs, masonry/src/widget/widget_state.rs
Apply many small tweaks I found while going over the documentation.
Rename some variables.
Add asserts to `BoxConstraints::constrain_aspect_ratio`.
Flesh out the WidgetState documentation.
Introduce the concept of "zombie flags".
=> Tweak documentation for readability

masonry/src/contexts.rs, masonry/src/widget/widget.rs
This makes it so that each context types has its most relevant, unique methods appear earlier in the documentation.
=> Reorder context impl blocks

masonry/src/app_driver.rs
Follow-up to #808
Also adds a test to limit the risk of future regression.
=> Make `DriverCtx` publicly constructable again

masonry/src/widget/text_area.rs
This matches the behavior of other frameworks in similar situations.
=> Move cursor to end of text area when text is changed

masonry/src/render_root.rs
Remove duplicate CursorIcon field.
=> Document RenderRoot fields

.github/workflows/ci.yml
`libegl1-mesa` seems to have been an old name, which is no longer accurate, and is not published for Ubuntu 24.
I don't know where this was publicised, but hopefully this change fixes CI?
=> Depend on `libegl-mesa0` instead of `libegl1-mesa`

masonry/examples/calc_masonry.rs, masonry/src/contexts.rs, masonry/src/event.rs, masonry/src/passes/accessibility.rs, masonry/src/passes/update.rs, masonry/src/widget/button.rs, masonry/src/widget/checkbox.rs, masonry/src/widget/split.rs, masonry/src/widget/tests/status_change.rs, masonry/src/widget/text_area.rs, masonry/src/widget/widget_state.rs
Rename has_pointer_capture to is_pointer_capture_target.
Rename has_focus to has_focus_target.
Rename is_focused to is_focus_target.
Add has_hovered flag.
Add ChildHoverChanged event.
=> Apply is/has naming convention for flags and methods

masonry/src/contexts.rs, xilem/examples/transforms.rs, xilem/src/lib.rs, xilem/src/one_of.rs, xilem/src/view/button.rs, xilem/src/view/checkbox.rs, xilem/src/view/flex.rs, xilem/src/view/grid.rs, xilem/src/view/image.rs, xilem/src/view/label.rs, xilem/src/view/portal.rs, xilem/src/view/progress_bar.rs, xilem/src/view/prose.rs, xilem/src/view/sized_box.rs, xilem/src/view/spinner.rs, xilem/src/view/textbox.rs, xilem/src/view/transform.rs, xilem/src/view/variable_label.rs, xilem/src/view/zstack.rs
Also significantly reduces the overhead from each View for supporting transforms.
Follow-up from #806
=> Move the `transform` related boilerplate in Xilem to a single View

masonry/src/doc/02_implementing_widget.md, masonry/src/doc/03_implementing_container_widget.md
Rewrite "Creating a new Widget" tutorial to interleave description of the Widget trait with example.
Go into more details.
Rewrite tutorials to use current WidgetMut syntax (the one with free functions instead of methods).
=> Rewrite tutorial

xilem/examples/emoji_picker.rs
This PR includes improvements to page selector.
Specifically it now shows the full percentage range instead of just the start of it, and it hides the buttons when you reach the end of the range.
For some reason it panics when I get to the end.
=> Emoji picker example improvements

Cargo.lock, Cargo.toml, masonry/examples/calc_masonry.rs, masonry/examples/custom_widget.rs, masonry/examples/grid_masonry.rs, masonry/src/testing/harness.rs, masonry/src/theme.rs, xilem/examples/mason.rs, xilem_web/web_examples/svgdraw/src/main.rs
This also lets us update to using `Color::from_rgb8()` when there is no need for alpha to be specified.
=> Update to Vello 0.4, Peniko 0.3.1, Color 0.2.3

.clippy.toml, .github/workflows/ci.yml, xilem/README.md, xilem/src/lib.rs, xilem/src/view/button.rs, xilem/src/view/checkbox.rs, xilem/src/view/flex.rs, xilem/src/view/grid.rs, xilem/src/view/label.rs, xilem/src/view/sized_box.rs
**Draft**
This PR is the proposal for xilem docs starting page. But I think I will be able to make some more commits to improve documentation.
=> xilem: Docs updating

Cargo.toml, masonry/src/event.rs, masonry/src/passes/anim.rs, masonry/src/render_root.rs, masonry/src/testing/harness.rs, masonry/src/testing/mod.rs, masonry/src/util.rs, masonry/src/widget/image.rs, masonry/src/widget/tests/mod.rs, masonry/src/widget/tests/status_change.rs, masonry/src/widget/widget.rs, masonry/src/widget/widget_pod.rs, masonry/src/widget/widget_state.rs
Remove outdated TODO comments.
Rewrite some other TODO comments.
Remove references to tarpaulin.
(cargo-tarpaulin is a tool used for code coverage. Masonry hasn't used it for years, and anyway we'll probably use `#[coverage]` annotations once they stabilize.)
=> Remove some cruft

masonry/src/app/tracing_backend.rs
These are no longer suppressed above it in the crate, so this isn't needed now.
Related to #449.
=> Remove extraneous `#[warn(...)]`

xilem/src/lib.rs
I wanted to create a custom button view, but when needing to pass to the masonry type could not convert the pod to a widgetpod.
So I'd like to make this method pub to allow that
=> xilem: make a Pod method pub to allow creating custom buttons in an app

xilem/src/lib.rs
I don't think there is a reason not to, and you need winit for some types so currently you must define the crate yourself, which risks version errors etc.
=> expose winit

Cargo.toml, masonry/src/core/event.rs, masonry/src/core/widget.rs, masonry/src/lib.rs, tree_arena/src/tree_arena_safe.rs, tree_arena/src/tree_arena_unsafe.rs, xilem/examples/calc.rs, xilem/examples/http_cats.rs, xilem/src/lib.rs, xilem_core/examples/filesystem.rs, xilem_core/src/lib.rs, xilem_core/src/message.rs, xilem_core/src/views/orphan.rs, xilem_core/tests/common/mod.rs, xilem_core/tests/one_of.rs, xilem_web/src/lib.rs, xilem_web/src/message.rs, xilem_web/web_examples/fetch/src/main.rs, xilem_web/web_examples/mathml_svg/src/main.rs, xilem_web/web_examples/svgtoy/src/main.rs, xilem_web/web_examples/todomvc/src/main.rs, xilem_web/web_examples/todomvc/src/state.rs
See linebender/linebender.github.io#88 (and some other earlier PRs)
A follow up like https://github.com/linebender/vello/pull/806 will also be needed, but that can come later.
=> Migrate to v5 of the Linebender lint set

Cargo.lock, masonry/Cargo.toml
These are the direct dependencies that have non-semver compatible updates (apart from wgpu).
=> Update `float-cmp` and `pollster`

Cargo.lock, Cargo.toml, masonry/examples/custom_widget.rs, masonry/src/widgets/label.rs, masonry/src/widgets/screenshots/masonry__widgets__label__tests__styled_label.png
This updates to the version using the updated objc2 and binding crates for Fontique.
It also has a minor API change.
=> Update to current `parley` `main`

masonry/src/widgets/text_area.rs
Without this, the updated text selection is neither painted nor reflected in an updated accessibility tree until the user presses a key.
=> Add missing `request_render` call when setting text selection from AccessKit

xilem_core/src/lib.rs, xilem_core/src/message.rs, xilem_core/src/views/orphan.rs
This removes the need to ignore `unused_qualifications`.
The `extern crate std` isn't *strictly* needed, but it will make future debugging easier (you can do `println` or `dbg!`, for example).
=> Make Xilem Core unconditionally `no_std`

.github/workflows/ci.yml
See https://github.com/linebender/vello/pull/833
=> Refactor LFS handling

masonry/src/core/contexts.rs, masonry/src/core/widget_state.rs, masonry/src/doc/06_masonry_concepts.md, masonry/src/passes/compose.rs, masonry/src/testing/harness.rs, masonry/src/widgets/portal.rs, masonry/src/widgets/tests/layout.rs
Document concepts of "layout rect" and "bounding rect".
Deprecate `local_layout_rect()` method.
Add `global_layout_rect()` method.
Remove `transform_changed()` method.
Improve bounding rect merging code.
Tweak `TestHarness::mouse_move_to`.
Tweak WidgetState doc.
=> Improve bounding rect code

masonry/src/widgets/split.rs, xilem/README.md, xilem/examples/http_cats.rs, xilem/src/lib.rs, xilem/src/view/mod.rs, xilem/src/view/split.rs
- Make the Masonry Split widget generic over its children (fixes a todo)
- Adds a new Xilem view for the widget
- Updated the `http_cats` example to use it for the main divider.
---
I'm unsure how exactly the `message` function works on a Xilem view as it was hard to find documentation on that, so I've tried my best to implement it, by looking at other views. Please double check that I did it right.
I also changed some defaults on the split widget. First, I changed `draggable` to default to true, since I believe this is the intended behaviour for the view, similar to how a button is not disabled by default.
I changed the constructors of the widget to not include the `split_axis` but rather let it be optional with vertical (row) being the default axis. I feel this made it more ergonomic to …
=> Add Xilem view for the Split widget

xilem/examples/http_cats.rs
While on slow internet connection I noticed that copyright notice is conflicting with the spinner: 
So I paired the image with the copyright notice to display it only when image is loaded. I hope this is not complicating the example code.
=> Pair image with copyright notice in http_cats example.

masonry/src/widgets/button.rs, masonry/src/widgets/checkbox.rs, masonry/src/widgets/flex.rs, masonry/src/widgets/grid.rs, masonry/src/widgets/label.rs, masonry/src/widgets/mod.rs, masonry/src/widgets/portal.rs, masonry/src/widgets/progress_bar.rs, masonry/src/widgets/prose.rs, masonry/src/widgets/root_widget.rs, masonry/src/widgets/scroll_bar.rs, masonry/src/widgets/sized_box.rs, masonry/src/widgets/split.rs, masonry/src/widgets/text_area.rs, masonry/src/widgets/textbox.rs, masonry/src/widgets/variable_label.rs, masonry/src/widgets/zstack.rs
Any new widget code needs to have full docs.
Not having `missing_docs` trigger by default for new widgets is quite bad.
See #875 and #882 for cases where this over-broad allow has bitten us.
The comment about not using `expect(missing_docs)` because of rust-analyzer is confusing to me; I don't run into an issue. It might have been https://github.com/rust-lang/rust/issues/130021, which is now fixed. That comment should have had a link to an upstream issue for more context.
=> Make `allow(missing_docs)` for widgets much more tightly scoped

Cargo.lock, masonry/Cargo.toml
`tempfile` on Unix pulls `rustix`, which has a 9.19s single-core build time on my machine, and was unused in our code.
`tempfile` is still a indirect dependency through `uds_windows`, which is fine because in that dependency path (windows-only) doesn't pull `rustix`.
=> Remove tempfile direct dependency

masonry/src/app/event_loop_runner.rs, masonry/src/core/contexts.rs, masonry/src/core/events.rs, masonry/src/doc/06_masonry_concepts.md, masonry/src/passes/event.rs, masonry/src/passes/update.rs, masonry/src/widgets/scroll_bar.rs, masonry/src/widgets/tests/status_change.rs
Create new PointerLost event.
No longer remove pointer capture on PointerLeave.
Fix small bugs and implementation errors.
Fixes #857.
Supersedes #858.
=> Fix pointer capture

masonry_core/src/widgets/mod.rs, masonry_core/src/widgets/text_area.rs, xilem/examples/mason.rs, xilem/examples/to_do_mvc.rs, xilem/src/lib.rs, xilem/src/view/textbox.rs
The textarea widget currently doesn't support multiline input because the Enter key is used to trigger the TextEntered action. This commit makes this behavior configurable by adding masonry_core::widgets::InsertNewline.
=> Add multiline text input support to TextArea

masonry_core/src/widgets/label.rs, masonry_core/src/widgets/text_area.rs
It's no longer correct to add the window-relative origin of the widget to the bounding rectangles of the text runs, since we now apply a transform on each widget's AccessKit node.
=> Fix bounding rectangles in accessibility nodes for text runs

masonry/src/event_loop_runner.rs
This is the default behavior in Chromium (when no configuration is provided) and is a better default than individual logical pixels.
=> masonry: Scroll by 120 logical pixels per line scroll increment.

.github/workflows/ci.yml, Cargo.toml, README.md, masonry/README.md, xilem/README.md, xilem/src/driver.rs, xilem/src/view/button.rs, xilem/src/view/checkbox.rs, xilem/src/view/task.rs, xilem/src/view/textbox.rs, xilem/src/view/worker.rs, xilem_core/README.md, xilem_core/src/deferred.rs, xilem_core/src/lib.rs, xilem_core/src/message.rs, xilem_core/tests/any_view.rs, xilem_core/tests/arc.rs, xilem_core/tests/array_sequence.rs, xilem_core/tests/base_sequence.rs, xilem_core/tests/one_of.rs, xilem_core/tests/tuple_sequence.rs, xilem_core/tests/vec_sequence.rs, xilem_web/README.md
With trait upcasting stabilised in Rust 1.86, we can make use of it in `DynMessage`.
This also makes `DynMessage` into a struct, because that reduces the risk of Rust Analyzer messing things up; it liked to confuse the `Message` trait with the `Message` generic. That is, the prior state was effectively `trait View<Message = Box<dyn Message>>`, which sometimes led to things like: `Box<dyn Box<dyn Message>>`.
=> Make `DynMessage` a struct, use trait upcasting (bump MSRV to 1.86)

masonry_core/src/widgets/portal.rs, masonry_core/src/widgets/virtual_scroll.rs
After https://github.com/linebender/xilem/pull/925, that 10x scrolling speed factor is no longer needed
=> Masonry: remove scrolling factor

Cargo.lock, Cargo.toml, masonry/src/event_loop_runner.rs, masonry_core/src/app/render_root.rs, masonry_core/src/passes/accessibility.rs, masonry_core/src/testing/harness.rs, xilem/examples/variable_clock.rs, xilem/src/driver.rs, xilem/src/lib.rs
With #936 stalling but Matt wanting AccessKit changes I decided to split out parts of #936 into this PR. This brings in Parley from March 25th, 2025 and that gets us the AccessKit update.
=> Update to Parley 2025-03-25.

masonry_core/src/widgets/sized_box.rs, masonry_core/src/widgets/text_area.rs, masonry_core/src/widgets/textbox.rs
Remove `with_padding_if_default` method and all related code.
Remove concept of "unset" padding.
Depends on #942.
=> Change how TextBox handles its padding

Cargo.toml, masonry/Cargo.toml, masonry_winit/Cargo.toml, tree_arena/Cargo.toml, xilem/Cargo.toml, xilem_core/Cargo.toml, xilem_web/Cargo.toml
* Ordering of sections: `package`, `features`, `dependencies`, `lints`, `profile`, `example`.
* Ordering of `package` fields: `name`, `version`, `description`, `keywords`, `categories`, `edition`, `rust-version`, `license`, `repository`, `homepage`, `exclude`.
I also removed the `homepage` field from non-Xilem crates, some stale exclusions, and the example scraping from `masonry` as it doesn't have examples.
=> Put `Cargo.toml` sections into consistent order.

ARCHITECTURE.md, README.md, masonry/README.md, masonry/src/lib.rs, masonry/src/widgets/scroll_bar.rs, masonry_winit/README.md, tree_arena/README.md, xilem/README.md, xilem_core/README.md, xilem_web/README.md
Despite the line diff number, there are almost no content changes in this PR.
* [One line per sentence.](https://linebender.org/wiki/formatting-scheme/)
* Updated badges. Of note is that the repo level badges are not finalized, but I updated to the latest checkpoint. After further discussion has happened in [Zulip](https://xi.zulipchat.com/#narrow/channel/419691-linebender/topic/Bikeshedding.20badges/with/452312397) we can once again update them.
* Reordered some sections to be in consistent order between crates.
* Gave `masonry` an actual `README.md`.
* Updated some references to `Masonry` with `Masonry Winit` to reflect the new state of things.
* A few miscellaneous tidy-ups.
=> Update `README.md` structures to the latest Linebender standard.

masonry/src/properties/corner_radius.rs
The `prop_changed` function of the other properties are public, so I thought this was a mistake.
=> Fix visiblity of a property function

Cargo.lock, Cargo.toml, masonry/Cargo.toml, masonry_winit/Cargo.toml, tree_arena/Cargo.toml, xilem/Cargo.toml, xilem_core/Cargo.toml, xilem_web/Cargo.toml
We skip Xilem 0.2.0 and go straight to 0.3.0 in order to synchronize the version with its companion packages that are expected to be updated in lock-step for now.
[The one exception is `tree_arena`](https://xi.zulipchat.com/#narrow/channel/419691-linebender/topic/Xilem.20version.20sync/with/517174026), which will retain its own version pacing, because it's likely to see fewer updates.
=> Prepare to release 0.3.0.

xilem_web/Cargo.toml
Apparently 5 is the maximum.
```
error: failed to publish to registry at https://crates.io
Caused by:
the remote server responded with an error (status 400 Bad Request): expected at most 5 keywords per crate
```
=> Remove 6th keyword from `xilem_web`.

masonry/src/core/contexts.rs, masonry/src/widgets/portal.rs, masonry/src/widgets/virtual_scroll.rs
The original rationale for which contexts to include this on doesn't really make sense;
there are legitimate reasons to use the scale factor in any context that deals with sizes or positions.
=> masonry: Allow `get_scale_factor()` in more contexts.

masonry/src/core/contexts.rs, masonry/src/core/mod.rs, masonry/src/core/widget_pod.rs, masonry/src/core/widget_state.rs, masonry/src/widgets/tests/transforms.rs, xilem/examples/emoji_picker.rs, xilem/src/lib.rs, xilem/src/view/button.rs, xilem/src/view/checkbox.rs, xilem/src/view/textbox.rs, xilem/src/view/transform.rs
This commit firstly introduces a breaking change by changing the WidgetPod constructors from taking an Affine to taking a WidgetOptions containing an Affine so that then the disabled boolean can be added to the WidgetOptions struct, allowing widgets to be created in disabled state. The Xilem views for the 3 currently existing input widgets then also gain a `disabled` method in order to change the disabled state.
=> xilem: support disabling inputs

masonry/src/widgets/progress_bar.rs, masonry/src/widgets/spinner.rs
- It is better to explicitly set min and max values rather than relying on defaults.
- We can then directly set the numeric value without doing any calculation.
- Setting text value on progress bar is not recommended unless there is strong reason to do so, the indeterminate case lacks translation anyway.
- A spinner can be considered as a progress indicator with indeterminate value.
=> Improve accessibility of ProgressBar and Spinner

Cargo.toml, xilem/Cargo.toml, xilem_core/Cargo.toml, xilem_web/Cargo.toml
This was originally added to the Cargo.toml without sufficient review, and it's not currently meaningfully managed by Linebender (e.g. there's no repository or review process for content).
Fixes https://github.com/linebender/xilem/issues/990
Further discussion for that issue should move to [#linebender > xilem.dev](https://xi.zulipchat.com/#narrow/channel/419691-linebender/topic/xilem.2Edev/with/520087715).
According to [Cargo's docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-homepage-field), the homepage field should be set to a homepage specifically for the package (which https://linebender.org does not currently fulfil).
We should probably have some mention that this is a Linebender crate and link to linebender.org. The exact shape of that is left as follow-up.
=> Remove the package `homepage`

tree_arena/src/tree_arena_safe.rs, tree_arena/src/tree_arena_unsafe.rs, tree_arena/tests/basic_tests.rs
This commit firstly implements root_ids and child_ids iterators so that the reparenting implementation can be properly tested.
Reparenting is then implemented in both the safe and the unsafe tree. For the unsafe tree no new unsafe code is introduced.
To make the tests more readable a new Node struct is introduced in the test code so that the tree after the reparenting can be compared with a single assert_eq!.
=> Implement reparenting in tree_arena

tree_arena/src/tree_arena_unsafe.rs
As discussed in https://github.com/linebender/xilem/pull/984#event-17825988627 - also make the comment for insert consistent between the safe and unsafe version of the tree
=> Reorder logic for reparent

masonry/src/passes/event.rs
If a widget is removed from the tree in response to an event it can cause a panic in the `on_event` function. I have seen this in a Xilem app when a `text_box(..).on_enter(..)` handler causes the text_box and its parent to be removed from the view. I have also seen it when a button responds to an accessibility click event causing it to be removed. I'm not certain if it is a subsequent event (like "key up") being delivered to the removed widget that tiggers the panic or if it is traversing the ancestor list for the same event when the ancestor has been removed.
=> masonry: fix panic on event when widget is not in the tree

masonry/src/passes/mod.rs, masonry/src/passes/update.rs
The hash was already included from the WidgetId Display impl.
=> Remove redundant hash sign in error messages

masonry/src/properties/background.rs, masonry/src/properties/border_color.rs, masonry/src/properties/mod.rs, masonry/src/theme.rs, masonry/src/widgets/button.rs, xilem/examples/calc.rs, xilem/src/style.rs, xilem/src/view/button.rs
Ideally, we'd want a system with full pseudo-class handling of properties, but until we implement that, this is a reasonable stopgap that lets the user customize *some* interactive behavior.
=> Add properties affecting hovered/disabled/active widgets

masonry/src/core/widget.rs, masonry/src/testing/helper_widgets.rs
The old signature took a WidgetRef, which external crates cannot construct.
=> Change find_widget_under_pointer signature

masonry/src/core/contexts.rs, masonry/src/widgets/flex.rs, masonry/src/widgets/portal.rs
This also removes the call to `set_paint_insets` in `Flex::layout`, which was redundant since the layout pass already computes paint insets on its own.
=> Refactor some layout methods to only use public items

masonry/src/passes/event.rs
Replaces the error log with a debug_panic.
This also moves the check outside the loop, since it was only ever going to fail in the first iteration anyway.
=> Tweak error case for event pass

masonry_winit/src/event_loop_runner.rs, xilem/examples/external_event_loop.rs
Instead of passing an `&EventLoop` to `MasonryState`, we pass an `EventLoopProxy` as that's all that it actually needs.
We also rename `proxy` to `event_loop_proxy`.
=> masonry_winit: Pass a EventLoopProxy

Cargo.lock, masonry_winit/Cargo.toml, masonry_winit/examples/calc_masonry.rs, masonry_winit/examples/custom_widget.rs, masonry_winit/examples/simple_image.rs, masonry_winit/src/event_loop_runner.rs
`masonry_winit` and its examples shouldn't have a direct dependency on `vello`. This is especially true for example code as it should be able to be copied and pasted without having to add its own dependency upon `vello`.
=> `masonry_winit`: Use `vello` via `masonry`

masonry_winit/src/event_loop_runner.rs, masonry_winit/src/lib.rs, xilem/src/window_view.rs
Continue down the path of making `masonry_winit` only contain what it actually provides rather than being some wrapper crate.
=> `masonry_winit`: Don't re-export `masonry::app::*`

masonry/src/doc/02_implementing_widget.md, masonry/src/doc/03_implementing_container_widget.md, masonry/src/doc/04_testing_widget.md, masonry/src/doc/04b_widget_properties.md
This fixes some things that have bitrotted due to API and other changes.
It also removes usages of `masonry_winit` where `masonry` should be used instead.
Dependencies like `kurbo`, `peniko`, `smallvec`, and `vello` should be referenced via their re-exports so that code outside of Masonry doesn't have to keep track of the versions and maintain their own dependencies.
=> Improve `masonry` docs

Cargo.lock, masonry_winit/Cargo.toml, masonry_winit/examples/calc_masonry.rs, masonry_winit/examples/custom_widget.rs, masonry_winit/examples/grid_masonry.rs
Some of the dev dependencies were unused or could be made to be unused by using the re-exports from `masonry`.
=> `masonry_winit`: Remove most dev dependencies

masonry/src/properties/background.rs, masonry/src/properties/border_color.rs, masonry/src/properties/border_width.rs, masonry/src/properties/corner_radius.rs
=> Give useful `reason`s for `missing_docs` of properties

xilem/src/any_view.rs, xilem/src/driver.rs, xilem/src/lib.rs, xilem/src/one_of.rs, xilem/src/view/button.rs, xilem/src/view/checkbox.rs, xilem/src/view/flex.rs, xilem/src/view/grid.rs, xilem/src/view/image.rs, xilem/src/view/label.rs, xilem/src/view/portal.rs, xilem/src/view/progress_bar.rs, xilem/src/view/prose.rs, xilem/src/view/sized_box.rs, xilem/src/view/spinner.rs, xilem/src/view/split.rs, xilem/src/view/task.rs, xilem/src/view/textbox.rs, xilem/src/view/variable_label.rs, xilem/src/view/worker.rs, xilem/src/view/zstack.rs, xilem/src/window_view.rs
Change code to remove reliance on private items.
Rename `ViewCtx::new_pod` to `ViewCtx::create_pod` to avoid ambiguity with constructor.
=> Prepare to split Xilem's lib.rs into multiple files

masonry/screenshots/flex_row_cross_axis_baseline.png, masonry/src/widgets/flex.rs, masonry/src/widgets/grid.rs, xilem/examples/emoji_picker.rs, xilem/examples/http_cats.rs, xilem/examples/mason.rs, xilem/examples/state_machine.rs, xilem/examples/to_do_mvc.rs, xilem/examples/variable_clock.rs, xilem/src/view/flex.rs, xilem/src/view/grid.rs
Add padding to to_do_mvc example.
Remove uses of sized_box from examples.
Fix flex baseline default alignment.
=> Add Properties to Flex and Grid

Cargo.lock, Cargo.toml, masonry_testing/Cargo.toml, masonry_testing/src/harness.rs
If you don't have the accessibility feature enabled in your OS then you don't run the accesskit_consumer code which can lead to accessibility being broken without you noticing.
Of course you should still do manual accessibility testing but this change ensures that the accesskit_consumer code at least doesn't crash if your app is tested with the TestHarness.
=> test: make TestHarness validate TreeUpdates returned by redraw

.clippy.toml, Cargo.lock, placehero/Cargo.toml, placehero/src/lib.rs, xilem/src/style.rs, xilem/src/view/grid.rs
This is an exploration into using the Mastodon API, continuing work on the hero app.
The actual changes here won't be all that useful, in the long term, but it's helpful for getting an understanding of how to use the API.
One big, unfortunate surprise is that we really need some HTML parsing (although only as described [in the docs](https://docs.joinmastodon.org/spec/activitypub/#sanitization)). That is something I'm not looking forward to!
One discovery in this PR is that our logging isn't set-up for the first `build` in Xilem. That makes sense with how logging is owned, but it's also very unfortunate).
I do intend to land this, to keep progress moving in a piecemeal way, and potentially to allow collaboration. It might be that hero app PRs should be largely rubber-stamped. Note that …
=> Placehero: Get initial list of statuses for first exploration

masonry_winit/src/event_loop_runner.rs
We need to garbage collect surfaces before window.
Tested on linux wayland.
Would be helpful if someone could test on windows and mac?
=> masonry_winit: fix libwayland-client crash due to wrong drop order

placehero/src/components.rs, xilem/examples/components.rs, xilem/examples/elm.rs, xilem/examples/emoji_picker.rs, xilem/examples/external_event_loop.rs, xilem/examples/flex.rs, xilem/examples/http_cats.rs, xilem/examples/mason.rs, xilem/examples/stopwatch.rs, xilem/examples/to_do_mvc.rs, xilem/examples/variable_clock.rs, xilem/examples/widgets.rs, xilem/src/view/flex.rs
This is a little papercut that I often run into, that the flex direction being defined after the sequence means that it can be hard to understand what element a piece of code relates to.
This is especially prevalent in nested flexes (e.g. a vertical flex containing horizontal flexes), as the changing flow direction is important to understand.
=> Add a flex row helper to Xilem

placehero/src/components.rs, placehero/src/lib.rs
Fairly small PR here, moving towards displaying a single timeline in context.
=> Placehero: Allow reblogs

Cargo.lock, masonry/Cargo.toml, masonry_testing/Cargo.toml, masonry_winit/Cargo.toml
This is handled in `masonry_core` and re-exported types from there so these direct dependencies are not used.
=> Remove unused direct deps on `web-time`

placehero/src/avatars.rs, placehero/src/components.rs, placehero/src/components/thread.rs, placehero/src/components/timeline.rs, placehero/src/lib.rs, placehero/src/main.rs
On the timeline (there is now a `View Replies` button on each post):
In a thread (i.e. once the button has been pressed):
Note that to get this image, I followed two "View Replies"; the first to get to [this post](https://mastodon.online/@raph/114530193780235287).
Note a few features:
- There is now a `⬅️ Back to Timeline` button in the sidebar. This jumps you back to Raph's timeline.
- The ancestors and descendants of the "thread" are now visible.
- There is a "replies" label after the "main" post in the new thread
A few caveats (which I'm treating as out of scope for this PR):
- The "continuity" of replies is not visible, i.e. which thread items are actually replies to the previous item or one before.
- The scroll position is not handled very well; every page change jumps to the top.
- …
=> Placehero: Add support for showing a single thread

masonry/src/widgets/flex.rs, xilem/src/view/flex.rs
This is already plural, so it doesn't become "childrens".
=> Fix possessive form of "children"

masonry/src/widgets/text_area.rs
This should be `TextArea`, not `Textbox`.
=> Fix `TextArea` trace span

masonry/src/doc/02_implementing_widget.md, masonry/src/doc/03_implementing_container_widget.md, masonry/src/doc/04b_widget_properties.md, masonry_core/src/core/contexts.rs, masonry_core/src/doc/06_masonry_concepts.md
These are not happening in `stable` Rust. Some remain that need slightly more consideration to resolve.
=> Fix some `clippy::doc_markdown` lints

masonry_winit/README.md, masonry_winit/examples/custom_widget.rs, masonry_winit/examples/grid_masonry.rs, masonry_winit/examples/hello_masonry.rs, masonry_winit/examples/simple_image.rs, masonry_winit/examples/virtual_fizzbuzz.rs, masonry_winit/src/event_loop_runner.rs, masonry_winit/src/lib.rs
The `run_with` function accepted the default properties as an argument, but `run` was creating them via a dependency on `masonry`.
This removes a usage of something only available in `masonry` from `masonry_winit`.
=> masonry_winit: Let caller pass default properties into run

Cargo.lock, masonry_core/src/lib.rs, masonry_testing/Cargo.toml, masonry_testing/src/harness.rs, masonry_testing/src/lib.rs, masonry_testing/src/modular_widget.rs, masonry_testing/src/recorder_widget.rs, masonry_testing/src/wrapper_widget.rs
We have things that are deps of `masonry_core`, `masonry`, and `masonry_testing` and if you use `masonry_core`, you need to know that and use the right versions.
Instead, we should be exporting these things from `masonry_core` and using them from there.
This updates `masonry_testing` to use things from `masonry_core` instead and subsequent commits can further improve upon this with the `masonry` crate and so on.
=> Re-export from `masonry_core`, use in `masonry_testing`

masonry_core/src/core/box_constraints.rs
A common layout use case is to have an inherent size (not necessarily the minimum) when the layout is unbounded.
`BoxConstraints::bounded_or` handles this on a per-axis basis, which is desirable in a number of cases, but is often not done because it is more code.
=> masonry_core: Add `BoxConstraints::bounded_or`

Cargo.lock, masonry_winit/Cargo.toml, masonry_winit/examples/calc_masonry.rs, masonry_winit/examples/custom_widget.rs, masonry_winit/examples/grid_masonry.rs, masonry_winit/examples/simple_image.rs, masonry_winit/examples/to_do_list.rs
Currently, the examples live in `masonry_winit` and use `masonry` with the `testing` feature enabled. Once these examples move back into `masonry`, then this becomes more annoying and it is easiest if they just depend separately on `masonry` and `masonry_testing`.
=> Use `masonry_testing` in masonry examples

masonry/src/properties/mod.rs, masonry/src/properties/text_color.rs, masonry/src/theme.rs, masonry/src/widgets/button.rs, masonry/src/widgets/checkbox.rs, masonry/src/widgets/label.rs, masonry/src/widgets/text_area.rs, xilem/examples/calc.rs, xilem/examples/emoji_picker.rs, xilem/examples/http_cats.rs, xilem/examples/mason.rs, xilem/examples/transforms.rs, xilem/examples/variable_clock.rs, xilem/src/style.rs, xilem/src/view/label.rs, xilem/src/view/prose.rs, xilem/src/view/text_input.rs, xilem/src/view/variable_label.rs
Add these properties to Label and TextArea.
Remove with_brush/set_brush methods.
Add TextColor and DisabledTextColor properties to Label view in Xilem.
Replace `.brush()` methods in TextEdit, Prose and VariableLabel views with `.text_color()` and `.disabled_text_color()` methods which set these properties.
Making TextColor and DisabledTextColor properties also means they can now be changed app-wide with DefaultProperties.
=> Add TextColor and DisabledTextColor properties.

README.md, masonry/README.md, masonry_winit/README.md, placehero/README.md, tree_arena/README.md, xilem/README.md, xilem_core/README.md, xilem_web/README.md
See [#linebender > Should we mention MSRVs in our crate READMEs?](https://xi.zulipchat.com/#narrow/channel/419691-linebender/topic/Should.20we.20mention.20MSRVs.20in.20our.20crate.20READMEs.3F/with/523325015) for rationale.
Also removes extra `<div class="rustdoc-hidden">` tag, which isn't needed when we use `cargo rdme`.
=> Remove detail sections of MSRV notices.

masonry/src/widgets/checkbox.rs
This avoids peeking through at the underlying type and uses the type as it is defined within the API.
=> Use `Dashes` for `dash_pattern`

README.md, docs/flake.lock, docs/flake.nix
Adds a basic nix flake with `devShells` that uses a rust environment to run on various targets, using the MSRV `rust-version` specified in the root `Cargo.toml`.
Fixes #66
=> Add a nix flake to support development on NixOS

masonry/screenshots/portal_scrolled_button_into_view.png, masonry/src/widgets/portal.rs, masonry_core/src/passes/event.rs, masonry_testing/src/harness.rs
This may be useful in cases where the user wants the harness to click something that would otherwise be scrolled away.
=> Add `TestHarness::scroll_into_view` method.

masonry/screenshots/sized_box_radial_gradient_background.png, masonry/screenshots/sized_box_sweep_gradient_background.png, masonry/src/properties/types/gradient.rs, masonry/src/properties/types/mod.rs, masonry/src/properties/types/unit_point.rs, masonry/src/widgets/sized_box.rs
Add `GradientShape::Radial` variant.
Add `GradientShape::Sweep` variant.
Add new `Gradient` constructors.
Add screenshot tests for new gradients.
This PR adds a lot of TODOs, but implementing gradients in a way that closely matches the CSS spec is just hard.
It still covers many common use-cases, and as such it's worth merging this before figuring out the full solution.
=> Add new gradient types

masonry/src/doc/color_rectangle.rs, masonry/src/doc/testing_widget.md, masonry/src/widgets/button.rs, masonry/src/widgets/checkbox.rs, masonry/src/widgets/flex.rs, masonry/src/widgets/grid.rs, masonry/src/widgets/image.rs, masonry/src/widgets/indexed_stack.rs, masonry/src/widgets/label.rs, masonry/src/widgets/portal.rs, masonry/src/widgets/progress_bar.rs, masonry/src/widgets/spinner.rs, masonry/src/widgets/split.rs, masonry/src/widgets/tests/ime_focused.rs, masonry/src/widgets/tests/status_change.rs, masonry/src/widgets/text_area.rs, masonry/src/widgets/text_input.rs, masonry/src/widgets/virtual_scroll.rs, masonry/src/widgets/zstack.rs, masonry_testing/src/harness.rs
This lets us skip downcast calls around edit_root_widget and root_widget (though we don't really use the latter).
=> Add type parameter to TestHarness

masonry/screenshots/portal_button_list_no_scroll.png, masonry/screenshots/portal_button_list_scroll_to_item_13.png, masonry/screenshots/portal_button_list_scroll_to_item_3.png, masonry/screenshots/portal_button_list_scrolled.png, masonry/src/widgets/portal.rs, masonry_testing/src/harness.rs
Constructing those types take a lot of time.
Caching them between render calls lets us considerably speed up tests with multiple snapshots. (Still doesn't help with single-snapshot tests.)
Re-enable a multi-screenshot test that was taking too long.
=> Cache RenderContext and VelloRenderer in TestHarness

masonry_testing/src/harness.rs
`MASONRY_BLESS_TEST` is used to treat all screenshots as valid.
This PR documents the flag and makes sure it works even when there's no reference file.
=> Document `MASONRY_BLESS_TEST` and have it handle new screenshots.

masonry_core/src/app/render_root.rs, masonry_core/src/core/contexts.rs, masonry_core/src/core/widget.rs, masonry_core/src/core/widget_state.rs, masonry_core/src/passes/layout.rs, masonry_core/src/passes/paint.rs, masonry_testing/src/modular_widget.rs, masonry_testing/src/recorder_widget.rs
Adds a new `post_paint()` method which paints content after children have been painted, and outside of the clip rect.
This will be useful for painting web-standards-accurate shadows, and other things which don't really fit our current painting model.
It's still missing some work; for instance, we should consider letting some widgets declare a shape which is considered "above" the widget's children when processing pointer events.
=> Add `Widget::post_paint()` method

masonry_core/src/app/render_root.rs, masonry_core/src/core/contexts.rs, masonry_core/src/core/mod.rs, masonry_core/src/core/widget_pod.rs, masonry_core/src/core/widget_tag.rs, masonry_core/src/passes/update.rs, masonry_testing/src/harness.rs, masonry_winit/examples/to_do_list.rs
Add a new WidgetTag type, which lets you access widgets without having to store their WidgetIds and lets you skip downcasting.
Tweak the to-do-list example to demonstrate how to use those tags.
Tags are similar to Selectors back in Druid and have a similar purpose: to carry type information between places in the code.
This is a first step towards adding a more generalized query system to Masonry.
=> Add WidgetTag

masonry_core/src/app/render_root.rs, masonry_core/src/core/widget_state.rs, masonry_testing/src/harness.rs
Fix `RenderRoot::needs_rewrite_passes`.
Fix `WidgetState::needs_rewrite_passes`.
Use both methods more consistently.
=> Add check that run_rewrite_passes doesn't saturate during tests

masonry/src/doc/color_rectangle.rs, masonry/src/tests/accessibility.rs, masonry/src/tests/anim.rs, masonry/src/widgets/tests/snapshots/masonry__widgets__tests__lifecycle_basic__app_creation.snap, masonry_core/src/core/contexts.rs, masonry_core/src/core/widget.rs, masonry_core/src/passes/accessibility.rs, masonry_testing/src/harness.rs, masonry_testing/src/modular_widget.rs
Follow-up to https://github.com/linebender/xilem/pull/711.
Fix `ColorRectangle` impl.
Add `access_node_children` test which checks that accessibility Node are set with the right children.
Run more early passes when creating TestHarness.
Add TestHarness getters for accessibility nodes.
Add new ModularWidget helper method.
=> Add accessibility test for Node children

masonry/src/tests/mutate.rs, masonry_core/src/passes/mutate.rs
Fix bug where a callback would panic if it was called after the associated widget was removed.
=> Add tests for mutate pass.

masonry/src/widgets/virtual_scroll.rs, masonry_winit/examples/virtual_fizzbuzz.rs, xilem/src/view/virtual_scroll.rs
That generic provided little to no value, and made using `VirtualScroll` a bit harder.
=> Masonry: Remove the generic on `VirtualScroll`

masonry/src/widgets/label.rs, masonry/src/widgets/text_area.rs, masonry_core/src/app/render_root.rs, masonry_core/src/core/contexts.rs, masonry_core/src/passes/layout.rs
This avoids issues where the initial render (say) doesn't have a given font, but the font is later loaded.
This is always the case with when Xilem accesses the font context, but I think it's also just generally the correct behaviour here.
This also fixes a minor issue with `request_render_all`, where it didn't take into account `post_paint`.
=> When a new font is loaded, relayout everything

masonry/src/tests/event.rs, masonry/src/tests/layout.rs, masonry/src/widgets/sized_box.rs, masonry/src/widgets/tests/layout.rs, masonry/src/widgets/tests/status_change.rs, xilem/src/view/sized_box.rs
Have `SizedBox::set_width()` and `SizedBox::set_height()` take a `Length`
Add `SizedBox::set_raw_width()` and `SizedBox::set_raw_height()` for use in Xilem
Add `SizedBox::size()`
Add `SizedBox::set_size()`
Follow-up to #1250.
=> Rewrite SizedBox setter methods

masonry/src/tests/event.rs, masonry_core/src/app/render_root.rs, masonry_core/src/doc/masonry_concepts.md, masonry_core/src/passes/event.rs, masonry_core/src/passes/update.rs, masonry_testing/src/harness.rs, masonry_winit/src/event_loop_runner.rs, xilem/src/any_view.rs, xilem/src/driver.rs, xilem/src/window_view.rs
This introduces an explicit fallback mechanism, for text events rather than the undocumented "only child of root" method we currently use.
=> Introduce "focus fallback" mechanism

masonry/src/tests/update.rs, masonry_core/src/core/events.rs, masonry_core/src/passes/update.rs
When a widget has pointer capture, keep hovering it if the cursor is over a child widget.
Remove some old focus chain code which set some focus flags incorrectly.
Check the right flags in code that tracks changes in has_xxx flags.
Follow-up to #1293.
=> Add status flags test and fix problems it uncovered

masonry/src/tests/accessibility.rs, masonry/src/tests/anim.rs, masonry/src/tests/compose.rs, masonry/src/tests/event.rs, masonry/src/tests/layout.rs, masonry/src/tests/paint.rs, masonry/src/tests/update.rs, masonry_testing/src/harness.rs
The name better conveys that the method drains the records from the given widget.
=> Rename `Harness::get_records_of` to `Harness::take_records_of`

masonry_core/src/app/render_root.rs, masonry_core/src/core/contexts.rs, masonry_core/src/passes/event.rs, masonry_core/src/passes/paint.rs
Document all undocumented fields.
Move `debug_paint` to `RenderRootState`.
=> Regularize `RenderRoot` and `RenderRootState` fields

masonry/src/tests/accessibility.rs, masonry/src/tests/anim.rs, masonry/src/tests/event.rs, masonry/src/tests/update.rs, masonry_testing/src/assert_any.rs, masonry_testing/src/lib.rs
The macros gives rich error messages for cases where we want apply a predicate to an entire collection.
=> Add `assert_any`, `assert_all` and `assert_none` helper macros.

xilem/examples/virtual_cats.rs
in case of failing to download the image.
I wanted to practice and get to know xilem a little.
When I found this TODO in the source code I thought this nice and silly little example might be a good fit, where I can cause no harm.
Here is the finished result which you may see running this without a connection
=> Add Error Handling to virtual cats example

placehero/src/components/timeline.rs
Previously, they were too close together (see screenshot in #1337)
=> Placehero: Add padding to the status list

xilem/src/view/text_input.rs
In current Xilem, this means that if you have a TextInput which starts disabled, you can never re-enable it.
This has impacted Placehero since #1354
=> Xilem: Fix handling of TextInput disabled property

masonry/screenshots/checkbox_hello_hovered.png, masonry/src/widgets/checkbox.rs
This makes things easier for Xilem, as it controls the source of truth for being checked. This operates somewhat similarly to `VirtualScroll`, and also addresses the issues found in https://github.com/linebender/xilem/pull/265.
I think it better reflects Masonry's low-level nature.
Working on this has uncovered another issue, which is that the tests aren't properly updated since #1314.
That PR added a large indicator, even when hovered.
However, those indicators are inflated to draw outside of the widget's area, so aren't captured here.
I don't have the motivation to fix this at the moment, but @tannal if you are willing to that would be great. A similar "flex" approach as in the new test from #1314 would be fine; just applying that to both tests (this should likelyalso use `WidgetTag`). …
=> Masonry: Give driver control over the Checkbox state

masonry/src/tests/update.rs, masonry_core/src/app/render_root.rs, masonry_testing/src/harness.rs, masonry_winit/src/event_loop_runner.rs
The Masonry `Window` struct was being created with a `0x0` size and a `1.0` scale factor. Initial layout and render passes ran with that. Then there would be an event for scale change (but still zero size) and another pass. Then there would be a size change event and useful work would finally take place.
This PR removes all that early useless work and creates the `Window` struct immediately with the correct info.
---
A bunch of places would ask Winit for the window size, including the `render` function. At least on Windows this would cause Winit to execute a syscall. That is needless overhead, especially in a hot path, because we already store that info in the `RenderRoot` struct.
This PR exposes that size info.
---
Masonry has been suffering from crashes on Windows 11 whenever a window …
=> Optimize and fix window resizing.

xilem/examples/to_do_mvc.rs
This adds the filter-buttons in the footer of TodoMVC via checkboxes (as we currently don't have better widgets for that...), in the future this should be updated with proper radio buttons.
=> xilem_masonry: Add filter ("All", "Active", "Completed") to todomvc example

placehero/login-design-doc.md, placehero/src/lib.rs, placehero/src/login_flow.rs
Our existing code makes a lot of architectural assumptions (in particular, that there's always one unchanging `Mastodon`) which become untrue when there's support for logging in. As such, adding login support will require a lot of refactoring, disguising the actually interesting changes.
Because of this, my plan is to develop the login feature in a more piecemeal fashion. First, I will develop a simple "login flow", which achieves "logging into an account, persisting (at least some of) the login information, and displaying some basic information about yourself". Then I will work to integrate this with the existing code, including fixing the assumptions.
To facilitate this, this PR shows an option between "login" and "Browse Anonymously" at app startup, i.e.:
The "Browse Anonymously" is …
=> Placehero: Start preparing for logged-in support by making a parallel version of the app

Cargo.lock, Cargo.toml, masonry/Cargo.toml, masonry_core/Cargo.toml, masonry_testing/Cargo.toml, placehero/Cargo.toml, xilem/Cargo.toml, xilem_web/Cargo.toml, xilem_web/web_examples/counter/Cargo.toml, xilem_web/web_examples/counter_custom_element/Cargo.toml, xilem_web/web_examples/elm/Cargo.toml, xilem_web/web_examples/fetch/Cargo.toml, xilem_web/web_examples/mathml_svg/Cargo.toml, xilem_web/web_examples/raw_dom_access/Cargo.toml, xilem_web/web_examples/spawn_tasks/Cargo.toml, xilem_web/web_examples/svgdraw/Cargo.toml, xilem_web/web_examples/svgtoy/Cargo.toml, xilem_web/web_examples/todomvc/Cargo.toml
This is largely here as a sanity check of Peniko 0.4.1, but we may as well do the upgrades.
Running Placehero still works.
`cargo upgrade --ignore-rust-version && cargo update`
I've not carefully checked what upgrades happened.
Not updated:
- kurbo, wgpu-profiler, for transitive dependency reasons
- Hashbrown, as transitive deps use old version still
- Html5Gum, as version upgrade slightly involved (spans are now returned)
- Vello, Parley, which are specific git versions
=> Update dependencies to get Peniko 0.4.1

masonry_testing/src/harness.rs
This fixes [#masonry > CI: Docs failing because of macros](https://xi.zulipchat.com/#narrow/channel/317477-masonry/topic/CI.3A.20Docs.20failing.20because.20of.20macros/with/542445707)
=> Fix the docs failure

xilem/src/view/text_input.rs
Following the recommendation in [1400](https://github.com/linebender/xilem/pull/1400), I've instead opted to improve the base documentation for the `text_input` widget.
=> Xilem: Improve documentation for the text_input widget

xilem/src/view/virtual_scroll.rs
The previous message was completely inscrutable!
=> Fix confusing log message in `VirtualScroll::message`

Cargo.lock, Cargo.toml, masonry_core/src/core/text.rs, masonry_core/src/util.rs
Upgrades Parley to the [0.6 release PR](https://github.com/linebender/parley/pull/426)
=> Upgrade to parley 0.6.0-dev
